//go:build ee

package eegraphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"
	graphql1 "platrium/internal/graphql"
)

// CreateSharedDrive is the resolver for the createSharedDrive field.
func (r *mutationResolver) CreateSharedDrive(ctx context.Context, name string) (*graphql1.Folder, error) {
	panic(fmt.Errorf("not implemented: CreateSharedDrive - createSharedDrive"))
}

// SetSharedDriveCreators is the resolver for the setSharedDriveCreators field.
func (r *mutationResolver) SetSharedDriveCreators(ctx context.Context, groupIds []string) ([]*graphql1.DirectorySubject, error) {
	panic(fmt.Errorf("not implemented: SetSharedDriveCreators - setSharedDriveCreators"))
}

// CanCreateSharedDrive is the resolver for the canCreateSharedDrive field.
func (r *queryResolver) CanCreateSharedDrive(ctx context.Context) (bool, error) {
	panic(fmt.Errorf("not implemented: CanCreateSharedDrive - canCreateSharedDrive"))
}

// SharedDriveCreators is the resolver for the sharedDriveCreators field.
func (r *queryResolver) SharedDriveCreators(ctx context.Context) ([]*graphql1.DirectorySubject, error) {
	panic(fmt.Errorf("not implemented: SharedDriveCreators - sharedDriveCreators"))
}
