// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package eegraphql

// A person, group or organization shown in a picker or on an access list.
type DirectorySubject struct {
	// USER | GROUP | TENANT
	Type  string  `json:"type"`
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Email *string `json:"email,omitempty"`
}

// A role as it should be shown when choosing one.
type RoleOption struct {
	Role         string   `json:"role"`
	Label        string   `json:"label"`
	Description  string   `json:"description"`
	Capabilities []string `json:"capabilities"`
}
