//go:build ee

package eegraphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"
	graphql1 "platrium/internal/graphql"
)

// ShareItem is the resolver for the shareItem field.
func (r *mutationResolver) ShareItem(ctx context.Context, input graphql1.ShareInput) (*graphql1.AccessGrant, error) {
	panic(fmt.Errorf("not implemented: ShareItem - shareItem"))
}

// RevokeAccess is the resolver for the revokeAccess field.
func (r *mutationResolver) RevokeAccess(ctx context.Context, grantID string) (bool, error) {
	panic(fmt.Errorf("not implemented: RevokeAccess - revokeAccess"))
}

// SetGeneralAccess is the resolver for the setGeneralAccess field.
func (r *mutationResolver) SetGeneralAccess(ctx context.Context, input graphql1.GeneralAccessInput) (*graphql1.GeneralAccess, error) {
	panic(fmt.Errorf("not implemented: SetGeneralAccess - setGeneralAccess"))
}

// SetInheritance is the resolver for the setInheritance field.
func (r *mutationResolver) SetInheritance(ctx context.Context, itemID string, inherit bool) (bool, error) {
	panic(fmt.Errorf("not implemented: SetInheritance - setInheritance"))
}

// ShareRoles is the resolver for the shareRoles field.
func (r *queryResolver) ShareRoles(ctx context.Context, itemID string) ([]*graphql1.RoleOption, error) {
	panic(fmt.Errorf("not implemented: ShareRoles - shareRoles"))
}

// GeneralAccessOptions is the resolver for the generalAccessOptions field.
func (r *queryResolver) GeneralAccessOptions(ctx context.Context, itemID string) ([]*graphql1.AccessLevelOption, error) {
	panic(fmt.Errorf("not implemented: GeneralAccessOptions - generalAccessOptions"))
}

// SearchDirectory is the resolver for the searchDirectory field.
func (r *queryResolver) SearchDirectory(ctx context.Context, query string, first *int, excludeAccessToItemID *string) ([]*graphql1.DirectorySubject, error) {
	panic(fmt.Errorf("not implemented: SearchDirectory - searchDirectory"))
}

// ItemAccess is the resolver for the itemAccess field.
func (r *queryResolver) ItemAccess(ctx context.Context, itemID string) (*graphql1.ItemAccess, error) {
	panic(fmt.Errorf("not implemented: ItemAccess - itemAccess"))
}

// SharedWithMe is the resolver for the sharedWithMe field.
func (r *queryResolver) SharedWithMe(ctx context.Context, first *int, after *string) (*graphql1.SharedItemConnection, error) {
	panic(fmt.Errorf("not implemented: SharedWithMe - sharedWithMe"))
}
