//go:build ee

package eegraphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"
	graphql1 "platrium/internal/graphql"
)

// TenantAuthConfigByAlias is the resolver for the tenantAuthConfigByAlias field.
func (r *queryResolver) TenantAuthConfigByAlias(ctx context.Context, alias string) (*graphql1.TenantAuthConfig, error) {
	panic(fmt.Errorf("not implemented: TenantAuthConfigByAlias - tenantAuthConfigByAlias"))
}
