package restapi

import (
	"fmt"

	"platrium/internal/auth"
	"platrium/internal/auth/protocol/local"
	"platrium/internal/authz"
	"platrium/internal/fsops"
	"platrium/internal/identity"
	"platrium/internal/infra/storage"
	"platrium/internal/notifications"

	"github.com/alexedwards/scs/v2"
	"github.com/caarlos0/env/v11"
)

// RestAPIEnv loads configuration for the REST API layer
type RestAPIEnv struct {
	HMACSecret string `env:"HMAC_SECRET" envDefault:"changeinprod"`
}

// RestAPI implements the StrictServerInterface generated by oapi-codegen
type RestAPI struct {
	FSOps               *fsops.FSOps
	Authz               authz.Authorizer
	ChunkStore          *fsops.ChunkStore
	StorageManager      *storage.Manager
	HMACSecret          string
	NotificationsBroker *notifications.Broker
	IdpStore            *auth.IdpStore
	UserStore           *identity.UserStore
	LocalUserStore      *local.LocalUserStore
	SessionManager      *scs.SessionManager
}

// NewRestAPI creates a new instance of the API
func NewRestAPI(fsOps *fsops.FSOps, az authz.Authorizer, chunkStore *fsops.ChunkStore, storageManager *storage.Manager, broker *notifications.Broker, idpStore *auth.IdpStore, userStore *identity.UserStore, localUserStore *local.LocalUserStore, sessionManager *scs.SessionManager) *RestAPI {
	var apiEnv RestAPIEnv
	if err := env.Parse(&apiEnv); err != nil {
		panic(fmt.Sprintf("failed to parse RestAPI env: %v", err))
	}

	return &RestAPI{
		FSOps:               fsOps,
		Authz:               az,
		ChunkStore:          chunkStore,
		StorageManager:      storageManager,
		NotificationsBroker: broker,
		IdpStore:            idpStore,
		UserStore:           userStore,
		LocalUserStore:      localUserStore,
		SessionManager:      sessionManager,
		HMACSecret:          apiEnv.HMACSecret,
	}
}
