package restapi

import (
	"fmt"
	"platrium/internal/auth/actor"

	"platrium/internal/auth"
	"platrium/internal/auth/protocol/local"
	"platrium/internal/auth/protocol/oidc"
	"platrium/internal/auth/token"
	"platrium/internal/fsops"
	"platrium/internal/identity"
	"platrium/internal/infra/storage"
	"platrium/internal/notifications"
	"platrium/internal/secrets"

	"github.com/alexedwards/scs/v2"
	"github.com/caarlos0/env/v11"
)

// RestAPIEnv loads configuration for the REST API layer
type RestAPIEnv struct {
	// NativeHTTPSRedirects lists https URL prefixes (universal links) that
	// native clients may use as redirect_uri. Custom schemes and loopback http
	// URLs are always allowed.
	NativeHTTPSRedirects []string `env:"AUTH_NATIVE_HTTPS_REDIRECTS" envSeparator:","`
}

// RestAPI implements the StrictServerInterface generated by oapi-codegen
type RestAPI struct {
	FSOps               *fsops.FSOps
	Actors              *actor.Resolver
	ChunkStore          *fsops.ChunkStore
	StorageManager      *storage.Manager
	HMACSecret          string
	NotificationsBroker *notifications.Broker
	IdpStore            *auth.IdpStore
	UserStore           *identity.UserStore
	LocalUserStore      *local.LocalUserStore
	SessionManager      *scs.SessionManager
	TokenStore          *token.Store
	CodeStore           *token.CodeStore
	DeviceStore         *identity.EntDeviceStore
	// OIDC starts OpenID Connect sign-ins (GET /auth/login for an OIDC provider).
	OIDC *oidc.Handler

	nativeHTTPSRedirects []string
}

// NewRestAPI creates a new instance of the API
func NewRestAPI(fsOps *fsops.FSOps, actors *actor.Resolver, chunkStore *fsops.ChunkStore, storageManager *storage.Manager, broker *notifications.Broker, idpStore *auth.IdpStore, userStore *identity.UserStore, localUserStore *local.LocalUserStore, sessionManager *scs.SessionManager, tokenStore *token.Store, codeStore *token.CodeStore, deviceStore *identity.EntDeviceStore) *RestAPI {
	var apiEnv RestAPIEnv
	if err := env.Parse(&apiEnv); err != nil {
		panic(fmt.Sprintf("failed to parse RestAPI env: %v", err))
	}

	return &RestAPI{
		FSOps:               fsOps,
		Actors:              actors,
		ChunkStore:          chunkStore,
		StorageManager:      storageManager,
		NotificationsBroker: broker,
		IdpStore:            idpStore,
		UserStore:           userStore,
		LocalUserStore:      localUserStore,
		SessionManager:      sessionManager,
		TokenStore:          tokenStore,
		CodeStore:           codeStore,
		DeviceStore:         deviceStore,
		HMACSecret:          secrets.FromEnv().SigningSecret(),

		nativeHTTPSRedirects: apiEnv.NativeHTTPSRedirects,
	}
}
