// Package restapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package restapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Presign a batch of chunks for download
	// (POST /files/downloadsession/chunks)
	DownloadSessionChunks(w http.ResponseWriter, r *http.Request, params DownloadSessionChunksParams)
	// Initialize a new download session
	// (POST /files/downloadsession/init)
	DownloadSessionInitialize(w http.ResponseWriter, r *http.Request)
	// Presign a batch of chunks for upload
	// (POST /files/uploadsession/chunks)
	UploadSessionChunks(w http.ResponseWriter, r *http.Request, params UploadSessionChunksParams)
	// Commit an upload session and finalize the file
	// (POST /files/uploadsession/commit)
	UploadSessionCommit(w http.ResponseWriter, r *http.Request, params UploadSessionCommitParams)
	// Initialize a new upload session
	// (POST /files/uploadsession/init)
	UploadSessionInitialize(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Presign a batch of chunks for download
// (POST /files/downloadsession/chunks)
func (_ Unimplemented) DownloadSessionChunks(w http.ResponseWriter, r *http.Request, params DownloadSessionChunksParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Initialize a new download session
// (POST /files/downloadsession/init)
func (_ Unimplemented) DownloadSessionInitialize(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Presign a batch of chunks for upload
// (POST /files/uploadsession/chunks)
func (_ Unimplemented) UploadSessionChunks(w http.ResponseWriter, r *http.Request, params UploadSessionChunksParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Commit an upload session and finalize the file
// (POST /files/uploadsession/commit)
func (_ Unimplemented) UploadSessionCommit(w http.ResponseWriter, r *http.Request, params UploadSessionCommitParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Initialize a new upload session
// (POST /files/uploadsession/init)
func (_ Unimplemented) UploadSessionInitialize(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// DownloadSessionChunks operation middleware
func (siw *ServerInterfaceWrapper) DownloadSessionChunks(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params DownloadSessionChunksParams

	headers := r.Header

	// ------------- Required header parameter "x-platrium-downloadsession" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-platrium-downloadsession")]; found {
		var XPlatriumDownloadsession string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "x-platrium-downloadsession", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-platrium-downloadsession", valueList[0], &XPlatriumDownloadsession, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x-platrium-downloadsession", Err: err})
			return
		}

		params.XPlatriumDownloadsession = XPlatriumDownloadsession

	} else {
		err := fmt.Errorf("Header parameter x-platrium-downloadsession is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "x-platrium-downloadsession", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadSessionChunks(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DownloadSessionInitialize operation middleware
func (siw *ServerInterfaceWrapper) DownloadSessionInitialize(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadSessionInitialize(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadSessionChunks operation middleware
func (siw *ServerInterfaceWrapper) UploadSessionChunks(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params UploadSessionChunksParams

	headers := r.Header

	// ------------- Required header parameter "x-platrium-uploadsession" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-platrium-uploadsession")]; found {
		var XPlatriumUploadsession string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "x-platrium-uploadsession", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-platrium-uploadsession", valueList[0], &XPlatriumUploadsession, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x-platrium-uploadsession", Err: err})
			return
		}

		params.XPlatriumUploadsession = XPlatriumUploadsession

	} else {
		err := fmt.Errorf("Header parameter x-platrium-uploadsession is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "x-platrium-uploadsession", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadSessionChunks(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadSessionCommit operation middleware
func (siw *ServerInterfaceWrapper) UploadSessionCommit(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params UploadSessionCommitParams

	headers := r.Header

	// ------------- Required header parameter "x-platrium-uploadsession" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("x-platrium-uploadsession")]; found {
		var XPlatriumUploadsession string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "x-platrium-uploadsession", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "x-platrium-uploadsession", valueList[0], &XPlatriumUploadsession, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "x-platrium-uploadsession", Err: err})
			return
		}

		params.XPlatriumUploadsession = XPlatriumUploadsession

	} else {
		err := fmt.Errorf("Header parameter x-platrium-uploadsession is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "x-platrium-uploadsession", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadSessionCommit(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadSessionInitialize operation middleware
func (siw *ServerInterfaceWrapper) UploadSessionInitialize(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadSessionInitialize(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/files/downloadsession/chunks", wrapper.DownloadSessionChunks)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/files/downloadsession/init", wrapper.DownloadSessionInitialize)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/files/uploadsession/chunks", wrapper.UploadSessionChunks)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/files/uploadsession/commit", wrapper.UploadSessionCommit)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/files/uploadsession/init", wrapper.UploadSessionInitialize)
	})

	return r
}

type DownloadSessionChunksRequestObject struct {
	Params DownloadSessionChunksParams
	Body   *DownloadSessionChunksJSONRequestBody
}

type DownloadSessionChunksResponseObject interface {
	VisitDownloadSessionChunksResponse(w http.ResponseWriter) error
}

type DownloadSessionChunks200JSONResponse FilesDownloadSessionChunksResponse

func (response DownloadSessionChunks200JSONResponse) VisitDownloadSessionChunksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DownloadSessionChunks401JSONResponse ErrorsUnauthorized

func (response DownloadSessionChunks401JSONResponse) VisitDownloadSessionChunksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DownloadSessionChunks500JSONResponse ErrorsEngineInternal

func (response DownloadSessionChunks500JSONResponse) VisitDownloadSessionChunksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DownloadSessionInitializeRequestObject struct {
	Body *DownloadSessionInitializeJSONRequestBody
}

type DownloadSessionInitializeResponseObject interface {
	VisitDownloadSessionInitializeResponse(w http.ResponseWriter) error
}

type DownloadSessionInitialize200JSONResponse FilesDownloadSessionInitResponse

func (response DownloadSessionInitialize200JSONResponse) VisitDownloadSessionInitializeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DownloadSessionInitialize404JSONResponse ErrorsNotFound

func (response DownloadSessionInitialize404JSONResponse) VisitDownloadSessionInitializeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DownloadSessionInitialize500JSONResponse ErrorsEngineInternal

func (response DownloadSessionInitialize500JSONResponse) VisitDownloadSessionInitializeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UploadSessionChunksRequestObject struct {
	Params UploadSessionChunksParams
	Body   *UploadSessionChunksJSONRequestBody
}

type UploadSessionChunksResponseObject interface {
	VisitUploadSessionChunksResponse(w http.ResponseWriter) error
}

type UploadSessionChunks200JSONResponse FilesUploadSessionChunksResponse

func (response UploadSessionChunks200JSONResponse) VisitUploadSessionChunksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UploadSessionChunks500JSONResponse ErrorsEngineInternal

func (response UploadSessionChunks500JSONResponse) VisitUploadSessionChunksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UploadSessionCommitRequestObject struct {
	Params UploadSessionCommitParams
	Body   *UploadSessionCommitJSONRequestBody
}

type UploadSessionCommitResponseObject interface {
	VisitUploadSessionCommitResponse(w http.ResponseWriter) error
}

type UploadSessionCommit200JSONResponse FilesUploadSessionCommitResponse

func (response UploadSessionCommit200JSONResponse) VisitUploadSessionCommitResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UploadSessionCommit500JSONResponse ErrorsEngineInternal

func (response UploadSessionCommit500JSONResponse) VisitUploadSessionCommitResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UploadSessionInitializeRequestObject struct {
	Body *UploadSessionInitializeJSONRequestBody
}

type UploadSessionInitializeResponseObject interface {
	VisitUploadSessionInitializeResponse(w http.ResponseWriter) error
}

type UploadSessionInitialize201JSONResponse FilesUploadSessionInitResponse

func (response UploadSessionInitialize201JSONResponse) VisitUploadSessionInitializeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type UploadSessionInitialize500JSONResponse ErrorsEngineInternal

func (response UploadSessionInitialize500JSONResponse) VisitUploadSessionInitializeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Presign a batch of chunks for download
	// (POST /files/downloadsession/chunks)
	DownloadSessionChunks(ctx context.Context, request DownloadSessionChunksRequestObject) (DownloadSessionChunksResponseObject, error)
	// Initialize a new download session
	// (POST /files/downloadsession/init)
	DownloadSessionInitialize(ctx context.Context, request DownloadSessionInitializeRequestObject) (DownloadSessionInitializeResponseObject, error)
	// Presign a batch of chunks for upload
	// (POST /files/uploadsession/chunks)
	UploadSessionChunks(ctx context.Context, request UploadSessionChunksRequestObject) (UploadSessionChunksResponseObject, error)
	// Commit an upload session and finalize the file
	// (POST /files/uploadsession/commit)
	UploadSessionCommit(ctx context.Context, request UploadSessionCommitRequestObject) (UploadSessionCommitResponseObject, error)
	// Initialize a new upload session
	// (POST /files/uploadsession/init)
	UploadSessionInitialize(ctx context.Context, request UploadSessionInitializeRequestObject) (UploadSessionInitializeResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// DownloadSessionChunks operation middleware
func (sh *strictHandler) DownloadSessionChunks(w http.ResponseWriter, r *http.Request, params DownloadSessionChunksParams) {
	var request DownloadSessionChunksRequestObject

	request.Params = params

	var body DownloadSessionChunksJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DownloadSessionChunks(ctx, request.(DownloadSessionChunksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DownloadSessionChunks")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DownloadSessionChunksResponseObject); ok {
		if err := validResponse.VisitDownloadSessionChunksResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DownloadSessionInitialize operation middleware
func (sh *strictHandler) DownloadSessionInitialize(w http.ResponseWriter, r *http.Request) {
	var request DownloadSessionInitializeRequestObject

	var body DownloadSessionInitializeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DownloadSessionInitialize(ctx, request.(DownloadSessionInitializeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DownloadSessionInitialize")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DownloadSessionInitializeResponseObject); ok {
		if err := validResponse.VisitDownloadSessionInitializeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UploadSessionChunks operation middleware
func (sh *strictHandler) UploadSessionChunks(w http.ResponseWriter, r *http.Request, params UploadSessionChunksParams) {
	var request UploadSessionChunksRequestObject

	request.Params = params

	var body UploadSessionChunksJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UploadSessionChunks(ctx, request.(UploadSessionChunksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UploadSessionChunks")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UploadSessionChunksResponseObject); ok {
		if err := validResponse.VisitUploadSessionChunksResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UploadSessionCommit operation middleware
func (sh *strictHandler) UploadSessionCommit(w http.ResponseWriter, r *http.Request, params UploadSessionCommitParams) {
	var request UploadSessionCommitRequestObject

	request.Params = params

	var body UploadSessionCommitJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UploadSessionCommit(ctx, request.(UploadSessionCommitRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UploadSessionCommit")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UploadSessionCommitResponseObject); ok {
		if err := validResponse.VisitUploadSessionCommitResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UploadSessionInitialize operation middleware
func (sh *strictHandler) UploadSessionInitialize(w http.ResponseWriter, r *http.Request) {
	var request UploadSessionInitializeRequestObject

	var body UploadSessionInitializeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UploadSessionInitialize(ctx, request.(UploadSessionInitializeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UploadSessionInitialize")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UploadSessionInitializeResponseObject); ok {
		if err := validResponse.VisitUploadSessionInitializeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
