// Package restapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package restapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fpvb9s40v8qAz0LPAng2I6TFFu/S9Om9aFpgqa9e9HLBWNxbHFLkSpJJXGLfPcDScmWbMmO27TXLvpi",
	"F6lFkfPn95sZzuhLFKs0U5KkNdHwS2TihFL0fx7nNum6/53RWzKZkobcz5lWGWnLyS+iFLlwf9hZRtEw",
	"MlZzOY3uO5ElidJec9b4NDekm5/ddyJNn3KuiUXDD/OF1Q07xbFXnfJlNf6LYus29lK/VlMu39KnnIxd",
	"lZmzrE2sDI25VbpdZokpbRa6OKHyyiZR2+yLN8gFjgVdp2QTxYICllLTKGLK5Sg83J8fiFrjzD2MExSC",
	"5JSurfpIsnEDSXf22ljKGp8aizY3m/Uv1rUqfXZ6/E/SfDJr9dFDZI0Vo2YreFNtFnP5kPmbxd5N8r/Q",
	"WmnTfSGnXNJIWudfsSo/o3E+5XKiNkuxWLrmvDfKnqpcstWTUjIGpy2gbNvuvcTcJkrzz/TNW55yQaZ7",
	"kuTy4ys0SdDexJpnlisZDaNLq3ls4fLV8d7g6Am8ojtwC+EGBWfoFkGG1lkSdp4cQpygxtiSNh0Q6pZ0",
	"jIYgobvdyBHUL4yG0X8+4N6kv/f06suTw/s/os4qDIJgz9WtFArZJRnDlfRymvbYIBmPSxdWlXiGNk5A",
	"TSB2G0CxDqwCHfaCTJPhU0kMWHEkvH/72sBE6S6cYJYRA7RwtD8AT+Bu1FkweaJ0ijYaRlzag8FCGy4t",
	"TUl7VONdwe2j/cFaqi9Ho0Knq1bntdioLSh5E4TwxBh3BkJxUVvxh6ZJNIz+r7fILr0itfQaj7wojefP",
	"dpLVzX8MH2m2d4MiJ0gxc/9lXE6BME5KDxBzbqE72EEDAQa7zkHcmopzgv/mLmJkkQvvjCXjrAQLr/SD",
	"jTiS3LbCbMIFFTmorufoucOYTQjcEid9KWkTwm9IG//e8jbnWfBK2KVY5nazqKdkuzCagFQOs+qGM2Id",
	"f6RA64BcLucGckOsu3rykmlKbba0TRu8/HZloq3r9QZTqhqoySj+dcM/N7z+TlkU4J7VrMwljGeWTNSp",
	"8fDJYTMPeUrX4efl/c9GZy/gRElL0u69m2UbZTXBHo1QONGzzKqpxizhMQoxA0MoiME//vUOfMICjK0j",
	"ARp/yBzTrorJlLYbHVc5vlMxe9WGVX0f7N8lNq9mx2L5da5Fg5cSglhwZ0PGNcUWLhpDq4usXnFPzc0w",
	"rZ3arsv77OHpIlbSIpfmmtTkOi6VratzKnAa8gV6b/EJCDQWSFBK0jr0JWgSMo5wgYbGws6L89PdebKZ",
	"g6gLx0KoWwNeMMfoMcG/837/IIbDM/6sYoWxUoJQOsXC/muSWpmbw3mFOFbBvEpozGCwM3jJn8Etl0zd",
	"7tby2eYEsCgYviW3FZpt6c3vmdhqB35TWluUaDA3VpHXIBBDzMr8lpJFhhYBJQNNMfHMPkZSq5tPpSm3",
	"LZxOitoPhTifRMMPW2Lgatk083LRaa0mBeAvNN1wlRsx87nJqa/GjoJljIDLcPfwinozbIis8Ors+KQ0",
	"WdXm45lnnSF9Q7qINdwEimyMNd4aCxG2MvCaS1EJz6YCW8xAaUaaGAhu7LxW9RVo6kDj1EnRWKeOy3sp",
	"Sj5xGd+4E2VMXTjDu4LbJs9cDgGEwTv+LASf7Rjeip064QeHgz//3IbzXwPaDdVGU/71aUgTurrS7ftG",
	"MYLR80eohmryba4Tv0spdNlWBAUM+BrJOb7bVBSleMfTPI2Gg/2nT/uDg8HR0dFRiNvh9/3HLJxgh7rT",
	"LmCWCZ9DlexlbNIBnuKUepmc7jbpnqGmef+prcgOi2CiBCMNSgPT/IY2unix97eVTQ1AaIPpo1aKi82+",
	"qlZ8oEKbqsDW+Hw5S1NyMS3E5jImh1ZBGanHKpc+/vuobDKK+YTHpWo+D7bVhZ0oz76u/AzvueKzC29y",
	"IVwxN69AAYUmZDOgO25C9pW58N27aGh1TptMXJFqXepwr81bS9y63aMLgVbzPIUTpQmOL0ZR5XYY9bv9",
	"bt/prTKSmPFoGB34n3xDJfHe6Dkz94Sacn+fnFKDYxxEubskAkqgu9D8gsvLc0hQMpPgR4Kdy+Oz173z",
	"0fOT3aIYCVYMyMsNaWcYhwPvzxFzZVBukxHL3hZLvVgaU7KkjS8l6C4Tvts3QWHIqR8No0856Zkzso+P",
	"EWdZVLVnsHhISU2trCu3ONDNG+CgP1jVuBTJ/asTJYTMi/QlEiqEogDkh57pXHfYPyyvDiS9kauR7S8T",
	"9lzssS7RLncH/QGrcC5qmBilu/RPuCNOQpW+iSajch1T14HkqN9/bAGX2qUNYl4GEcmt98QweZqinrlH",
	"l+fg2+QwB4iL78o0INQhiaR1wjqUerzBDUeXyZl7gMIATt2dzZU287AxYhcerWQsjgX39x+cBxOlgRuT",
	"+9/mTeNmGL9WMYr3hrSXuAAkGftMsdmjWXV1yHFfjyUOh/dL+B48olsbRhct0Cu7owm6kjKOiRgxD7PD",
	"/v5jw6zW1m4Q6DiOyfh7dl5Z+VOC3uMowN4/CeE5FIKNsfkt2VzLEGXjXLsCRcx87iz5wDwb/t/MYe0u",
	"jM0oPqPoe6NnabL4S8On5rmXZOEkOABcIKi6b4K9Gz/48tVQYwTzgzEeUuzZ6fEi3pSVXFuUavZkmLN9",
	"zzi0Msz7HYv+ZrEouNej8aREY0C1u/CYXtlYLYDYW/QpmiH+kqSDKRmwPKW9UMnXS+6VEdoiVfsrYX0K",
	"lxt/uVm8VUY4T5lVYjTOu1arTl9lhppvUWbe7WVFrb23pPf21efjM/IBM88fTM+HTBh/8/VR+Vq2QhHG",
	"tal1IFJ1oIhTh/RweY+u1lCaS27bCR3uhYJ/JsDAz2UmdmGe1/zz45PXprgehrIFy55FM4f92rLJvZHQ",
	"C3miH0izaifvZyBZraH0FRT7fU3dinU1Eki6XUHyWsKF3s9DM2gY3K1+eeKzpW991UYcjR20EA1CIg2n",
	"czldpVbDAG37TFnT7ufJk2tGvf8TAq8bVm5N4F8rKwWEbEMRP9dpp0iY+7hbVNG0rXaGJ1wGps5nDAJn",
	"KrdFJelHA8WnMUtUqs5W1xElSPf3JEptSvkTEKU+4fvlibIdcregzLZFXP34SgnHyFguQzYpZmftBV05",
	"YWq7jK0MwX5A5dY6gX0Qmve/vzRfgWVv/VB5lHWSXzAmkvNBNjrHaDK5sL9GEVXHYBPY/Wd0bsMQYetH",
	"hTYqoxsSKvOfW4W1USfyw78osTYb9nrCrUuUscODfr/fw4z7T1KKw76UkTocen91/98AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
