// Package restapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package restapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fxbc+O2kv4rXdxTtXaVLF/Gnj3RedLIdka747HLmiQPyawLIlsijkGAAUDbypT/+xYupEgJ1GXGnjhZ",
	"PyRjixTQ6OvXjW5/iWKR5YIj1yrqfYlUnGJG7I/9Qqdd878LvEaVC67QfJxLkaPUFO1LpNDpzS3lifkl",
	"QRVLmmsqeNSL3ot70ClVIPH3ApUG8y5yTWOiMenB6Gw0Gl5+hJ2xFPcK5W4HTs9+Hg7OQEjoX13BzhiJ",
	"RAla3CLf7UadCHmRRb1fI//VqBO5b0SdqH91FX3uRHqWY9SLlJaUT6PHTpTgHY3xhgYIHKGG+xQ5VIcA",
	"qjwNZreltTAjlJl1lp5o5IRrv8vS00KhDD977ESGO1RiYs5VvlhfsNy2U+P1/KBi/G+MtdmkEpeQ9A+8",
	"djwPCCzPb+5QKsuCAK2xSPAmTgljyKe4zLR3ROHb40IyGL3v7x2dvAUxAZ0ixIwi1/+pQGEsUYNd6A4l",
	"nVCUsHP1P4MzGB2dvN0NspaTLLDZKBX3HLSwGxjmADFC4vb3UytZtd/PcwWMKt0B7E678Ft0xYiWtMhg",
	"IiTQq1Rw/C0yWlV7NPgw/C0KkpIzoidCZsvkDC9HHbjoD8w//Y+n15fD0w50u134xWhRLlEh1zVmgFX+",
	"KVUaJSZAFBBw+vgvr3hj+w1q3yQcSJ4HSZKYUImxvikkXSbrlxQlGi4p5EmNVRON8p7IRPWAQFwoLTL4",
	"6foDWBvHDhBgQuRjEt9CqnVun+0cHv1X96B70D3swK+93uHnDjARE5YKw1/CZ5ALqXc7hpsEYsEndFqY",
	"w5kVFBScGuUiDBjlt8GzKE10QNSXOfm9qBh3R1iBgHEqMAFLoXBCLzkRWHrBlho8W9Jrr3GbGFKb66s2",
	"0GK9Zddfbt10YA//FTYr0bjUG2K/a3TX/BQlROOephmGxBAXUvrNmoL4JAu0hmP1WGJiXDZhkJFbyqcN",
	"j14TwlgIhoRbL/mQU4lqK2paHGcZWEq/v9bbM6L0TaG25EXpfFa6gtXytY7akuuXa0hlgbA599eowgeq",
	"dLsCOluxP1KNmf3hHxInUS/6j/15WN/3MX2/rmOP1cZESjJbOk+5djuB9nRutdZgU6oC5TcJmallZftA",
	"J2ikYny6eeNfIDKqrfoRF/dBp0SD4GwGfjXnOmnC0OhfJWHK9ZujuXQp1zhFuUK8Cyde7Q8+iCnl7eds",
	"BQY0ydtQQU6Uuhcy2US58joSWEdkK1a7I5SRMcObDHUqkqbmLNGXUT50Dw8XlaUTVZ70xkopuADHB32j",
	"NObBpyYOFGr94f17rYe+OO//bFDGrFU6m9BqwkOYC5ZV68lc3KT6pl+7lf6rQqWtpLcTrCXhysTiun/s",
	"X30cRZ3ofHAR8I4LBM8X6PhtWkn8ZB63s7eNdQ0EuAEHzTqL31pHU5uuN2D/MpD/6hC1ECuthzIosFDG",
	"sOCe6hROzz6cfTqDfYPX970j3f9Ck8cgHqpEvICza7lPFy6N/1MWDQse43r0UyohDScLZ1IKqbrvSNIq",
	"1gyVItMWx9m24BmfUo5DrlFywkJiGRdTyicbIKb5qysOcC7kmCaJY+AT0P9R6HNRONDxBMv9xEmJI795",
	"yXPKUHUHacFv3xOVBpIlLWmsq7TsPT6AedFgaZoQ8xLkRBvJwM7bY4hTIkmsUSoD8e9RxkQhpPiwG5nY",
	"ZF+MetH//kr2Jgd7P3z+8vb48R8hBXaEnYp7zgRJRqgMTrV0qlblojwxuVsovdRxalLK2CwA/j2T3JRV",
	"BJNm0SnHBBK/pUlclMEMXRiQPDeZloaTwyOwsc3YShXkNkALGXnwYe/k8GhlFFyM0v5Mn1uF18KjVnxn",
	"n9vInSTUMIiwq8Ybq9BecMurknl2b1cfqbO/D7c423PZV0Zy819uUD+SOC0lgCYDT/ABdogCpwa7RkBU",
	"q5pwnPwqESWoCWWq5rhK5izFUXvojZk45LQdf04oC5d+hqdl2cK8YqgvKQ1peC33WkxanVTcKv41W68g",
	"coq6C8MJcGF0VtzRBJOO3ZIRbRS5fJ0qk68n6316eZotedOmXna5cN3lI8mwzqAQU+zXFf0DQ2FREwbm",
	"WYPLlMN4plEtoPa3x2E7pBneuI8X178YXpzBQHCNXO99muVraVWOH0FVGMhZrsVUkjylMWEmziJhmMB/",
	"//LJpyAk1sYIiLKbVDptAHwJoFZD2Pn2nRrb6zysn3dj+S5Y83K09a/fFJIFpFTVqfZcbQKugq51Xgww",
	"u6xX08au7Wf5Kd88XMSCa0K5ukExuYnLwzaPc87I1MULYqVFJ2CSbkCGmS2ycUiJSlEZg3NmqDTsnF2e",
	"71bBplKiLvQZE/cKLGHGoscIvxUHB29iOL6g78KVD7f+iqBWxma3nydHC6hQQjCCwc7Rj/Qd3FOeiPvd",
	"RjxbHwDmgOFbYps/2ZbSfM7A1tjwm8LaHKJBxSwf18AZBpuV8S1DTRKiia1DS4yR5vopglqTfSLLqG6x",
	"6dRjP8LY5STq/bqlDnxeZE0FF82pxcQr/JXEOyoKxWY2Npnji7ExwdJHwMil5faglg1rPCu8v+gPSpbV",
	"eT6eWatTKO9Qel9DlTORtb7GcmNOwlYMXlEvKNUzBLDZDIRMbEGfUaUrrGoRaOZKpEbLlDbHMXEvI5xO",
	"TMRXZkeTvsEFefC2rYrcxBAgcPSJvnPOZzsLb9WdpsEfHR/985/b2PzXKO0atBHMoV2ZmRhcadb9KBKE",
	"4ekToKEGfetx4rNAoVEbCHI6YDGSEXw3BIoy8kCzIot6R4c//HBw9Obo5OTkxPlt9/nhUwIn2LHXZyTP",
	"mY2hgu/nyaQDNCNT3M/5dDd4W0YkVjefbSDbvQQTwRKUICQkkt7hWhHP1/422BRQhDY1fVKkOF/sq7Di",
	"hgdahwJb/fNolmVofJrzzaVPdqWC0lOPRcETdwVLFagcYzqhcXk0GwfbcGEnKvKvg5/uewZ8duFjwZgB",
	"cxUCBcIkkmQG+ECVi768YLawHfW0LHAdi2tUrQod5mtVqYpqs3rt+lhIhP7VMKplh9FB96B7YM4tcuQk",
	"p1EvemM/sgWV1ErDVQWr+GfFJVQoehLG5uHxHscQG5XlGnIyRVsGdEpmWbZHub/1zU2yiQoIcKLpXXWl",
	"KuyzLoy0kPaxonzKcK9QaO/q65JGsNf1VU3bwx1dSO4026QFSxfO9p5Wiy68cw0dlZIIzmZdGPKYFQlC",
	"eanmijrudrx+aV67JjeyNapsVXKYGCRX6LS6m42cXFHpdyKZlYmCv9Ws+7F/K5e9u8C50T3ZUifFY1ON",
	"jKLZD5wnsbI9Ojh4NiK8w7JULBtSWRxLiUEUcYyYYNI1qnj8hDQtV41byPFgLhYFS2wBpOAJSqWJV5eS",
	"3KSwtRfKbY0S1Ixr8uDJPnxqshvF2ADh/ThGZbPDovamp+bNU1Mzr1yvJGVSvmbpOHl6YS5U7APEjJww",
	"0bxvfakqsozImbdGyyYgUF4sP3aixs2HoWOKOnT3q7SvqLhOHutlSJ4r79MMVvKR1N+XWz8TdgpmtYHf",
	"8bnNMnA5/xV2+ZIU/KUpluFt2eBl1aKf5zbZDMfKC8ILC8hcIuGCX4ZWmzwyM4ml+4pbcDDsgpGQe0qV",
	"azFwMQ4TSFFiSyALql+9HeI5w1Ko7eLPiEzN69fXqPQalV6O83A2YlwGWDVdjkn2Nt65EYahbsRT+7mL",
	"PT6z40nH9yW5cNWphS537091Fz6RW1SAk4lJaGiWYUKJxjav4bapvEZOJMlQo1S2sEcNJSZxKHvKeq7N",
	"rGnqnRpnF/Oez0tu4DiYiEk0UuUCvAwrbF+V47xtdGBcuA7XFIkxHsjIDMY2AZgUrAsv0UqOn5qaqktg",
	"jaMh3HiZCW36FzSplBKFNPnNCzSfa7wTt2V7te3Fz/OaCTmN38+LsgchbEEjLXIF5i1IkNE7lLMyt/Q2",
	"4xr77n1GGRPGKJ9Cvee/JdQyJPKq8IXf//fa/RoDgjHAKAkYLSljQCfKiwB0vPYVCKeF/auPyqj8+eCi",
	"hhufQGlHqCuVfSZoWG8k3AgSfh9reQV6r0b+bJHKVw/rdl4FKiamlLdWH4acaupyRQ744PaH0egSUsIT",
	"lZJbhJ1R/+LD/uXwdLDrK6CuUq2qmmfY2IdJfu1fXUZ1+JAz2zE7IUxhx6G83wuUszrMy78J5705OAp5",
	"OkeS+a0TeZs1rzHhJOguCzbd8/EVW22vsUa/bJc+VArSWtTo18YlFRBXY7+jpDaUo4BMCeVKA5lfzQyT",
	"K6utqDQZM2p7TMi8hCGBKlXYz6r6fktJTcSE/aRQWoqfM3Q1piv+jHJGc3LitZj3tMU8o0dO7ZvuWThA",
	"Flb/M540a79zte9BUsvPQyAMduygqFYet7mBxQSVlmLmvjZu1vbaTMAS+adAp5cnxilcFvUKv+uXCIbX",
	"69ploRcgmzUnwK1Ds/PCzjMlRJOwFC4w+h43bRf49/AADan9iBoG3oKML6+Lb0L27aDNrN0Kf3aDOBYl",
	"XZz3a1fCVVksHGjCknSTWs8ZSpbGwV7Dyd8snDjxWm0cVPPcc62u5qnCCn2NCWLm+3MWOiAmUmQw780A",
	"LaaoU5SuvDtvi2j8ZYN6awRpVgLgmmgERjOqXX//skF88nNaz2YPjdm915ui71VAeGlGc/YQp8S47YFV",
	"dCHr6fKEMlT7Zd++d+D78zbYsCX9iNxos0FhNMM91z7U7OhamtCaZym247A55FUo2zs3/1aJDFrqasFx",
	"qpZrFIez5hn2w17uW7n2Fs69feL99Ja7wUjddzblTQbYXuPck5ps2WlPYNwYinSGVJ9XI1Oj6a43NPq8",
	"wqQppysyLlcSY66dx9rnoiV2ocKD9nl/8EEtBEDfEhu2YftuOUOx1qDn9ETf0czqjeIvwcga/cpfYWKv",
	"FbqtrK5hBBzvlzR5pcG51uJNI6ibC1sebLbR0nZWNyZogg3azhu4QOp2p3y6bFqB+aztI2XjdC8nTq6Y",
	"JPxTDHjVLNzWBvzXikpOQ7YxETs2tKIL3j4HwsuZgPrgwYRyZ6nVCAsjM1FojyTt5ImfvF4wpfro3ipD",
	"cdT9PQ2lMQT3AgylOUD2lzeU7TR3C5PZFsQ1t69BuASVptxFEz+a1Q7oygGmtmRsacbqOyC31gG/jbT5",
	"8Pmp+Qpddk3wFnmUOMm+MEbk1ZykHZGRqAqm/xogqqmDIWW3f6XBLOg87MKogL1BSvAOmcjtNL97N+pE",
	"drYsSrXOe/v71Z+q7L05ODjYJzm1E89+sy+lp3abPn5+/L8AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
