// Package restapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package restapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fpvb9s40v8qAz0LPAng2I6TFFu/S9Om9aFpgqa9e9HLBWNxbHFLkSpJJXGLfPcDScmWbCm227TXLvpi",
	"F6lEkfPn95sZzvhLFKs0U5KkNdHwS2TihFL0fx7nNum6/53RWzKZkobc40yrjLTl5BdRily4P+wso2gY",
	"Gau5nEb3nciSRGmvOWt8mxvSze/uO5GmTznXxKLhh/nC6oad4tirTvmxGv9FsXUbe6lfqymXb+lTTsZu",
	"IzNnWZvAGRpzq/QGEhebbCpkm2XxBrnAsaDrlGyimH/ILaWmUb6Uy1F4uT8/ELXGmXsZJygEySldW/WR",
	"ZOMGku7stbGUNb41Fm1u1itfrGtV+uz0+J+k+WTW6p1NZI0Vo2YreFOtF3P5kPmXxd5N8r/QWmnTfSGn",
	"XNJIWtISxar8jMb5lMuJWi/FYukD571R9lTlkq2elJIxOKXmc9q2ey8xt4nS/DN985anXJDpniS5/PgK",
	"TRK0N7HmmeVKRsPo0moeW7h8dbw3OHoCr+gO3EK4QcEZukWQoXWWhJ0nhxAnqDG2pE0HhLolHaMhSOhu",
	"N3IE9AujYfSfD7g36e89vfry5PD+j6izCoMg2HN1K4VCdknGcCW9nKYVd1wyHpcurCrxDG2cgJpA7DaA",
	"Yh1YBTrsBZkmw6eSGLDiSHj/9rWBidJdOMEsIwZo4Wh/AJ7A3aizYPJE6RRtNIy4tAeDhTZcWpqS9qjG",
	"u4LbR/uDB6m+HIoKna5anddio7ag5E0QwhNj3BkIxUVtxR+aJtEw+r/eIq/0iqTSazzyojSeP9tJVjf/",
	"MXyk2d4Nipwgxcz9l3E5BcI4KT1AzLmF7mAHDQQY7DoHcWsqzgn+m7uIkUUuvDOWjLMSLLzSGxtxJLlt",
	"hdmECypyTF3P0XOHMZsQuCVO+lLSJoTfkDb+u+VtzrPglbBLscztZlFPyXZhNAGpHGbVDWfEOv5IgdYB",
	"uVzODeSGWHf15CXTlNpsaZs2ePntJKa0qtcbTKlqoCaj+M8N/9zw+TtlUYB7V7MylzCeWTJRp8bDJ4fN",
	"POQpXYfHy/ufjc5ewImSlqTdezfL1spqgj0aoXCiZ5lVU41ZwmMUYgaGUBCDf/zrHfiEBRhbRwI0/pA5",
	"pl2Vkilt1zqucnynYvaqDav6buzfJTavZsdi+XWuRYOXEoJYcGdDxjXFFi4aQ6uLrF5xT831MK2d2q7L",
	"+2zzdBEraZFLc01qch2XytbVORU4DfkCvbf4BAQaCyQoJWkd+hI0CRlHuEBDY2Hnxfnp7jzZzEHUhWMh",
	"1K0BL5hj9Jjg33m/fxDD4Rl/VrHCWClBKJ1iYf8HklqZm8N5hThWwbxKaMxgsDN4yZ/BLZdM3e7W8tn6",
	"BLAoGL4ltxWabenN75nYagd+U1pblGgwN1aR1yAQQ8zK/JaSRYYWASUDTTHxzD5GUqubT6Upty2cTora",
	"D4U4n0TDD1ti4GrZNPNy0WmtJgXgLzTdcJUbMfO5yamvxo6CZYyAy3D38Ip6M6yJrPDq7PikNFnV5uOZ",
	"Z50hfUO6iDXcBIqsjTXeGgsRtjLwA5eiEp5NBbaYgdKMNDEQ3Nh5reor0NSBxqmTorFOHZf3UpR84jK+",
	"cSfKmLpwhncFt02euRwCCIN3/FkIPtsxvBU7dcIPDgd//rkN578GtGuqjab869OQJnR1pdv3jWIEo+eP",
	"UA3V5FtfJ36XUuiyrQgKGPA1knN8t6koSvGOp3kaDQf7T5/2BweDo6OjoxC3w/P9xyycYIe60y5glgmf",
	"Q5XsZWzSAZ7ilHqZnO426Z6hpnnnqa3IDotgogQjDUoD0/yG1rp4sfe3lU0NQGiD6aNWiovNvqpW3FCh",
	"dVVga3y+nKUpuZgWYnMZk0OroIzUY5VLH/99VDYZxXzC41I1nwfb6sJOlGdfV36G71zx2YU3uRCumJtX",
	"oIBCE7IZ0B03IfvKXPjuXTS0Oqd1Jq5I9VDqcJ/NW0vcut2jC4FW8zyFE6UJji9GUeV2GPW7/W7f6a0y",
	"kpjxaBgd+Ee+oZJ4b/ScmXtCTbm/T06pwTEOotxdEgEl0F1ofsHl5TkkKJlJ8CPBzuXx2eve+ej5yW5R",
	"jAQrBuTlhrQzjMOB9+eIuTIot8mIZW+LpV4sjSlZ0saXEnSXCd/tm6Aw5NSPhtGnnPTMGdnHx4izLKra",
	"M1g8pKSmVtaVWxzo5g1w0B+salyK5P7ViRJC5kX6EgkVQlEA8qZnOtcd9g/LqwNJb+RqZPvLhD0XezyU",
	"aJe7g/6AVTgXNUyM0l36J9wRJ6FK30STUbmOqetActTvP7aAS+3SBjEvg4jk1ntimDxNUc/cq8tz8G1y",
	"mAPExXdlGhDqkETSOmEdSj3e4Iajy+TMvUBhAKfuzuZKm3nYGLELj1YyFseC+/sPzoOJ0sCNyf2zedO4",
	"GcavVYzivSHtJS4AScY+U2z2aFZdHW/c12OJw+H9Er4Hj+jWhtFFC/TK7miCrqSMYyJGzMPssL//2DCr",
	"tbUbBDqOYzL+np1XVv6UoPc4CrD3b0J4DoVgY2x+SzbXMkTZONeuQBEznztLPjDPhv83c1i7C2Mzis8o",
	"+t7oWZop/tLwqXnuJVk4CQ4AFwiq7ptg78YPvnw11BjB/GCMhxR7dnq8iDdlJdcWpZo9GeZs3zMOrQzz",
	"fseiv1ksCu71aDwp0RhQ7S48plc2Vgsg9hZ9imaIvyTpYEoGLE9pL1Ty9ZJ7ZYS2SNX+SlifwuXGX24W",
	"X5URzlNmlRiN867VqtNXmaHmW5SZd3tZUWvvLem9ffX5+IzcYOb5g+m5yYTxN18fla9lKxRhXJtaByJV",
	"B4o4dUgPl/fo6gFKc8ltO6HDvVDwzwQY+LnMxC7M85p/f3zy2hTXw1C2YNmzaOawX1s2udcSeiFP9ANp",
	"Vu3k/QwkqzWUvoJiv6+pW7GuRgJJtytIfpBwofezaQYNg7vVX574bOlbX7URR2MHLUSDkEjD6VxOV6nV",
	"MEDbPlPWtPt58uQDo97/CYEfGlZuTeBfKysFhGxDET/XaadImPu4W1TRtK12hidcBqbOZwwCZyq3RSXp",
	"RwPFT2OWqFSdrT5ElCDd35MotSnlT0CU+oTvlyfKdsjdgjLbFnH14yslHCNjuQzZpJidtRd05YSp7TK2",
	"MgT7AZVb6wR2IzTvf39pvgLL3vqh8ijrJL9gTCTng2x0jtFkcmF/jSKqjsEmsPuf0bkNQ4StHxXaqIxu",
	"SKjM/9wqrI06kR/+RYm12bDXE25doowdHvT7/R5m3P8kpTjsSxmpw6H3V/f/DQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
