// Package restapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package restapi

import (
	"time"
)

// Defines values for AuthAuthMeResponseAuthKind.
const (
	AuthAuthMeResponseAuthKindAPP     AuthAuthMeResponseAuthKind = "APP"
	AuthAuthMeResponseAuthKindDEVICE  AuthAuthMeResponseAuthKind = "DEVICE"
	AuthAuthMeResponseAuthKindSESSION AuthAuthMeResponseAuthKind = "SESSION"
)

// Valid indicates whether the value is a known member of the AuthAuthMeResponseAuthKind enum.
func (e AuthAuthMeResponseAuthKind) Valid() bool {
	switch e {
	case AuthAuthMeResponseAuthKindAPP:
		return true
	case AuthAuthMeResponseAuthKindDEVICE:
		return true
	case AuthAuthMeResponseAuthKindSESSION:
		return true
	default:
		return false
	}
}

// Defines values for AuthClientKind.
const (
	AuthClientKindAPP    AuthClientKind = "APP"
	AuthClientKindDEVICE AuthClientKind = "DEVICE"
)

// Valid indicates whether the value is a known member of the AuthClientKind enum.
func (e AuthClientKind) Valid() bool {
	switch e {
	case AuthClientKindAPP:
		return true
	case AuthClientKindDEVICE:
		return true
	default:
		return false
	}
}

// Defines values for AuthPushRequestTransport.
const (
	APNS AuthPushRequestTransport = "APNS"
	FCM  AuthPushRequestTransport = "FCM"
)

// Valid indicates whether the value is a known member of the AuthPushRequestTransport enum.
func (e AuthPushRequestTransport) Valid() bool {
	switch e {
	case APNS:
		return true
	case FCM:
		return true
	default:
		return false
	}
}

// AuthAuthMeResponse defines model for Auth.AuthMeResponse.
type AuthAuthMeResponse struct {
	// AuthKind How this request authenticated: SESSION (browser), DEVICE or APP (bearer token).
	AuthKind AuthAuthMeResponseAuthKind `json:"auth_kind"`

	// DeviceId Set when auth_kind is DEVICE.
	DeviceId *string `json:"device_id,omitempty"`

	// DisplayName The user's name as the database has it now, not as it was at sign-in.
	DisplayName string `json:"display_name"`

	// Email The address the user is signed in with, as the database has it now (an external provider keeps it current).
	Email    string `json:"email"`
	TenantId string `json:"tenant_id"`
	UserId   string `json:"user_id"`
}

// AuthAuthMeResponseAuthKind How this request authenticated: SESSION (browser), DEVICE or APP (bearer token).
type AuthAuthMeResponseAuthKind string

// AuthAuthorizeRequest defines model for Auth.AuthorizeRequest.
type AuthAuthorizeRequest struct {
	AppVersion *string `json:"app_version,omitempty"`

	// CodeChallenge Base64url SHA-256 of the client's secret code_verifier (PKCE S256).
	CodeChallenge string `json:"code_challenge"`

	// Name Shown to the user and in the Devices/Apps list, e.g. "Platrium for iPhone" or "Platrium CLI".
	Name string `json:"name"`

	// Platform IOS, MACOS, ANDROID, ... When present the client is registered as a device; when absent it is an app.
	Platform *string `json:"platform,omitempty"`

	// RedirectUri Where to send the user afterwards: a custom URL scheme, a loopback http URL (127.0.0.1, [::1], localhost, any port), or a configured https universal link.
	RedirectUri string `json:"redirect_uri"`

	// State Opaque client value echoed back on the redirect.
	State *string `json:"state,omitempty"`
}

// AuthAuthorizeResponse defines model for Auth.AuthorizeResponse.
type AuthAuthorizeResponse struct {
	RedirectTo string `json:"redirect_to"`
}

// AuthClient defines model for Auth.Client.
type AuthClient struct {
	AppVersion *string   `json:"app_version,omitempty"`
	CreatedAt  time.Time `json:"created_at"`

	// Current True for the credential making this request.
	Current    bool           `json:"current"`
	ExpiresAt  *time.Time     `json:"expires_at,omitempty"`
	Id         string         `json:"id"`
	Kind       AuthClientKind `json:"kind"`
	LastUsedAt time.Time      `json:"last_used_at"`
	Name       string         `json:"name"`
	Platform   *string        `json:"platform,omitempty"`
}

// AuthClientKind defines model for AuthClient.Kind.
type AuthClientKind string

// AuthClientListResponse defines model for Auth.ClientListResponse.
type AuthClientListResponse struct {
	Clients []AuthClient `json:"clients"`
}

// AuthCreateClientRequest defines model for Auth.CreateClientRequest.
type AuthCreateClientRequest struct {
	// ExpiresInDays Lifetime in days; omit for a token that only expires when idle.
	ExpiresInDays *int32 `json:"expires_in_days,omitempty"`
	Name          string `json:"name"`
}

// AuthLoginRequest defines model for Auth.LoginRequest.
type AuthLoginRequest struct {
	Email    string  `json:"email"`
	IdpId    string  `json:"idp_id"`
	Password *string `json:"password,omitempty"`
}

// AuthLoginResponse defines model for Auth.LoginResponse.
type AuthLoginResponse struct {
	AvailableMethods *[]string `json:"available_methods,omitempty"`
	ChallengeToken   *string   `json:"challenge_token,omitempty"`
	NextStep         *string   `json:"next_step,omitempty"`
	Status           string    `json:"status"`
}

// AuthMFAVerifyRequest defines model for Auth.MFAVerifyRequest.
type AuthMFAVerifyRequest struct {
	ChallengeToken string `json:"challenge_token"`
	Code           string `json:"code"`
	Method         string `json:"method"`
}

// AuthPushRequest defines model for Auth.PushRequest.
type AuthPushRequest struct {
	Token     string                   `json:"token"`
	Transport AuthPushRequestTransport `json:"transport"`
}

// AuthPushRequestTransport defines model for AuthPushRequest.Transport.
type AuthPushRequestTransport string

// AuthTokenRequest defines model for Auth.TokenRequest.
type AuthTokenRequest struct {
	Code         string `json:"code"`
	CodeVerifier string `json:"code_verifier"`
}

// AuthTokenResponse defines model for Auth.TokenResponse.
type AuthTokenResponse struct {
	DeviceId  *string    `json:"device_id,omitempty"`
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// Id Token ID, usable with DELETE /auth/clients/{id}.
	Id string `json:"id"`

	// Token Bearer token. Only shown once.
	Token string `json:"token"`
}

// ErrorsBadRequest defines model for Errors.BadRequest.
type ErrorsBadRequest struct {
	Message *string `json:"message,omitempty"`
}

// ErrorsEngineInternal defines model for Errors.EngineInternal.
type ErrorsEngineInternal struct {
	Debuginfo string `json:"debuginfo"`
}

// ErrorsForbidden defines model for Errors.Forbidden.
type ErrorsForbidden struct {
	Message *string `json:"message,omitempty"`
}

// ErrorsNotFound defines model for Errors.NotFound.
type ErrorsNotFound struct {
	Message *string `json:"message,omitempty"`
}

// ErrorsUnauthorized defines model for Errors.Unauthorized.
type ErrorsUnauthorized struct {
	Message *string `json:"message,omitempty"`
}

// FilesChunkHash Strict SHA-256 Hex Hash validation pattern (64 characters, lowercase hex)
type FilesChunkHash = string

// FilesDownloadSessionChunksRequest defines model for Files.DownloadSessionChunksRequest.
type FilesDownloadSessionChunksRequest struct {
	// Indices Batch of chunk indices to request presigned download URLs for. Capped at 512 items.
	Indices []int32 `json:"indices"`
}

// FilesDownloadSessionChunksResponse defines model for Files.DownloadSessionChunksResponse.
type FilesDownloadSessionChunksResponse struct {
	// Chunks A key-value map mapping each requested index (as string) to its presigned chunk download details.
	Chunks map[string]FilesDownloadSessionPresignedChunk `json:"chunks"`
}

// FilesDownloadSessionInitRequest defines model for Files.DownloadSessionInitRequest.
type FilesDownloadSessionInitRequest struct {
	// FileId ID of the file to download
	FileId string `json:"file_id"`

	// Version Optional file version to target. If not provided, the latest version is used.
	Version *string `json:"version,omitempty"`
}

// FilesDownloadSessionInitResponse defines model for Files.DownloadSessionInitResponse.
type FilesDownloadSessionInitResponse struct {
	// FileName Name of the file
	FileName string `json:"file_name"`

	// FileSize Total size of the file in bytes
	FileSize int64 `json:"file_size"`

	// MimeType MIME Content-Type of the file
	MimeType string `json:"mime_type"`

	// SessionId Cryptographically sealed JWT token acting as the download passport
	SessionId string `json:"session_id"`
}

// FilesDownloadSessionPresignedChunk defines model for Files.DownloadSessionPresignedChunk.
type FilesDownloadSessionPresignedChunk struct {
	// DownloadUrl The client-direct Presigned download URL for the chunk.
	DownloadUrl string `json:"download_url"`
}

// FilesUploadSessionChunksRequest defines model for Files.UploadSessionChunksRequest.
type FilesUploadSessionChunksRequest struct {
	// ContainsEofChunk Flag indicating if last element in hashes is the last (EOF) chunk in the file. Allows Chunk to be < 4MiB.
	ContainsEofChunk *bool `json:"contains_eof_chunk,omitempty"`

	// Hashes Batch of SHA-256 chunk hashes to authorize. Capped at 512 items (2GiB window).
	Hashes []FilesChunkHash `json:"hashes"`
}

// FilesUploadSessionChunksResponse defines model for Files.UploadSessionChunksResponse.
type FilesUploadSessionChunksResponse struct {
	// Chunks A key-value map mapping each authorized ChunkHash string directly to its metadata and receipts.
	Chunks map[string]FilesUploadSessionPresignedChunk `json:"chunks"`
}

// FilesUploadSessionCommitChunk defines model for Files.UploadSessionCommitChunk.
type FilesUploadSessionCommitChunk struct {
	// Hash SHA-256 Hash of Chunk Previously used to obtain Presign Status
	Hash FilesChunkHash `json:"hash"`

	// Receipt Cryptographic HMAC receipt authorized by the server for this chunk
	Receipt string `json:"receipt"`
}

// FilesUploadSessionCommitRequest defines model for Files.UploadSessionCommitRequest.
type FilesUploadSessionCommitRequest struct {
	// Chunks Strictly ordered list of chunks forming the master file manifest sequence. Max items support a 2TiB file.
	Chunks []FilesUploadSessionCommitChunk `json:"chunks"`
}

// FilesUploadSessionCommitResponse defines model for Files.UploadSessionCommitResponse.
type FilesUploadSessionCommitResponse struct {
	// FileId The created FileNode ID
	FileId string `json:"file_id"`
}

// FilesUploadSessionInitRequest defines model for Files.UploadSessionInitRequest.
type FilesUploadSessionInitRequest struct {
	// FileName Name of the file
	FileName string `json:"file_name"`

	// FileSize Size of the file in bytes. Max size 2TiB.
	FileSize int64 `json:"file_size"`

	// MimeType MIME Content-Type of the file (e.g. application/pdf, image/png)
	MimeType string `json:"mime_type"`

	// ParentId ID of the parent folder or drive
	ParentId string `json:"parent_id"`
}

// FilesUploadSessionInitResponse defines model for Files.UploadSessionInitResponse.
type FilesUploadSessionInitResponse struct {
	// SessionId Cryptographically sealed JWT token acting as the session_id passport
	SessionId string `json:"session_id"`
}

// FilesUploadSessionPresignedChunk defines model for Files.UploadSessionPresignedChunk.
type FilesUploadSessionPresignedChunk struct {
	// Receipt Symmetric HMAC authorization receipt bound to this specific session and chunk.
	Receipt string `json:"receipt"`

	// UploadUrl The client-direct Presigned upload URL. Null if the chunk already exists.
	UploadUrl *string `json:"upload_url"`
}

// AuthIdpRedirectParams defines parameters for AuthIdpRedirect.
type AuthIdpRedirectParams struct {
	Idp      string  `form:"idp" json:"idp"`
	ReturnTo *string `form:"return_to,omitempty" json:"return_to,omitempty"`
}

// DownloadSessionChunksParams defines parameters for DownloadSessionChunks.
type DownloadSessionChunksParams struct {
	XPlatriumDownloadsession string `json:"x-platrium-downloadsession"`
}

// UploadSessionChunksParams defines parameters for UploadSessionChunks.
type UploadSessionChunksParams struct {
	XPlatriumUploadsession string `json:"x-platrium-uploadsession"`
}

// UploadSessionCommitParams defines parameters for UploadSessionCommit.
type UploadSessionCommitParams struct {
	XPlatriumUploadsession string `json:"x-platrium-uploadsession"`
}

// AuthAuthorizeJSONRequestBody defines body for AuthAuthorize for application/json ContentType.
type AuthAuthorizeJSONRequestBody = AuthAuthorizeRequest

// AuthCreateClientJSONRequestBody defines body for AuthCreateClient for application/json ContentType.
type AuthCreateClientJSONRequestBody = AuthCreateClientRequest

// AuthSetPushJSONRequestBody defines body for AuthSetPush for application/json ContentType.
type AuthSetPushJSONRequestBody = AuthPushRequest

// AuthLocalUserLoginJSONRequestBody defines body for AuthLocalUserLogin for application/json ContentType.
type AuthLocalUserLoginJSONRequestBody = AuthLoginRequest

// AuthVerifyJSONRequestBody defines body for AuthVerify for application/json ContentType.
type AuthVerifyJSONRequestBody = AuthMFAVerifyRequest

// AuthTokenJSONRequestBody defines body for AuthToken for application/json ContentType.
type AuthTokenJSONRequestBody = AuthTokenRequest

// DownloadSessionChunksJSONRequestBody defines body for DownloadSessionChunks for application/json ContentType.
type DownloadSessionChunksJSONRequestBody = FilesDownloadSessionChunksRequest

// DownloadSessionInitializeJSONRequestBody defines body for DownloadSessionInitialize for application/json ContentType.
type DownloadSessionInitializeJSONRequestBody = FilesDownloadSessionInitRequest

// UploadSessionChunksJSONRequestBody defines body for UploadSessionChunks for application/json ContentType.
type UploadSessionChunksJSONRequestBody = FilesUploadSessionChunksRequest

// UploadSessionCommitJSONRequestBody defines body for UploadSessionCommit for application/json ContentType.
type UploadSessionCommitJSONRequestBody = FilesUploadSessionCommitRequest

// UploadSessionInitializeJSONRequestBody defines body for UploadSessionInitialize for application/json ContentType.
type UploadSessionInitializeJSONRequestBody = FilesUploadSessionInitRequest
