package restapi

import (
	"fmt"

	"platrium/internal/fsops"
	"platrium/internal/infra/storage"

	"github.com/caarlos0/env/v11"
)

// RestAPIEnv loads configuration for the REST API layer
type RestAPIEnv struct {
	HMACSecret string `env:"HMAC_SECRET" envDefault:"changeinprod"`
}

// RestAPI implements the StrictServerInterface generated by oapi-codegen
type RestAPI struct {
	FSOps          *fsops.FSOps
	ChunkStore     *fsops.ChunkStore
	StorageManager *storage.Manager
	HMACSecret     string
}

// NewRestAPI creates a new instance of the API
func NewRestAPI(fsOps *fsops.FSOps, chunkStore *fsops.ChunkStore, storageManager *storage.Manager) *RestAPI {
	var apiEnv RestAPIEnv
	if err := env.Parse(&apiEnv); err != nil {
		panic(fmt.Sprintf("failed to parse RestAPI env: %v", err))
	}

	return &RestAPI{
		FSOps:          fsOps,
		ChunkStore:     chunkStore,
		StorageManager: storageManager,
		HMACSecret:     apiEnv.HMACSecret,
	}
}
