package restapi

import "platrium/internal/fsops"

// RestAPI implements the ServerInterface generated by oapi-codegen
type RestAPI struct {
	FSOps *fsops.FSOps
}

// NewRestAPI creates a new instance of the API
func NewRestAPI(fsOps *fsops.FSOps) *RestAPI {
	return &RestAPI{FSOps: fsOps}
}
