// Package restapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package restapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3Fhbb9u4Ev4rA54+tIBjO04ctH5L0vbEB70ETXv2oZsNxtLYYkuRKkk5cQP/98WQkq9yc8Fu0d2HALLE",
	"y3zffN9wmFuRmLwwmrR3YnArXJJRjuHxlbXGuvYrPZGahtqT1aj4Q2FNQdZLCsNSGpUTqceGf/hZQWIg",
	"nLdST8R83hKWvpXSUioGn1eGXrbqoWb0hRIv5i3xWipy7dOs1F/P0GVxbZdYWXhptBiIC29l4uHi7Hiv",
	"1z+CM7oBHghTVDJFHgQFeo4Tnh4dQpKhxcSTdS1Q5ppsgo4go5tnoiWqgWIg/viMe+Pu3ovL26PD+RPR",
	"2sRQB/apUAbTC3JOGh2idB/oW0nOb3OSGO1RandFZnyV8NhtNK8VTkDqVCbopZ6AHINC54EU5aQ9SA0Z",
	"uowcSAc+o/j16av3r59BWJJH8PuxVNSGY6XMtYMQGHgDI4Lfy273IIHDt/KkvcQ1MkYRagYW198O7QR9",
	"koEZL6iO+1XheANY+sxY+Z3acIpFQSmgh/5+D6Sn3MHT3n/lCVxLnZrrZ7x1eM37PLE0FgPxn85SdZ1K",
	"cp3N/M9bIsebYZza3++1RC519XN/AQetxdmW0ipku2XWmE1XGO2oIZ3hOz9hmkomCdX52oi7ca1teG7J",
	"yYmmNOzMUa0n4Bi+0mxviqokyLHgv4I1QphkS/JTWJAFUa2QSkuJVzNOkvQOcvKYokdAnYKlhGTh3YoY",
	"alo26KsA35c+k+fSn9YyX+cuq6yMSr0fi8HnB2rgcpOahfsZtRlXgj+3NJWmdGoGpaOU4ZsRWxAqquHC",
	"oy+dCEADDduyP7WzwpuJxSKTCZy9PT6tKVvlfDQLrnNkp2RhbCz4TLpoke3q0aBLsQzhQQTvrjYLeTbV",
	"SzUDY1OylIKSzjNncQLHnrNoGE6OzjMcqfhZyzE5D4531Am14S3eVN52ZVEY6wGh91GexOLzMIfv1M66",
	"4XuHvefPH+L5x4h2t+cZ2JVMt1n9mBEkltBTCrzuO5MSDF/emfp6wXvGN9Q/yHhYS2NO2+G9w5w4x/XJ",
	"0HSghelOfm+YfiG/r03nQ2Y08+SiBnhSSDznnPWDXgyE1P7oUITsybzMxaC3/+JFt3fQ6/f7/Vi34/tl",
	"CqX2NCHL0RRoSftGrocv61jiIBgblZIFYyG1ckp3kr5cu7VC2ioDD0rHLrG4OKgRw1pVQaVm4AgVpfC/",
	"3z6CN19JAyahA0BXVZZ6MSjQOXbbnThXArgnoI0jaAvSzip5Mctz4soSK2RdGWP/VdfLkSl1qMKhNrqC",
	"EjmWSQ0tnEbBru0meZYhzqvSqh3uU5K034tnHSyAQJwHnz68acO7UiluqZjQ2L2gsoTpDOhGungG6lIp",
	"HCkSA29Luovilah+VMB52qIblp5XF+cKvZVlDqfGEhyfD0VLTMm6CKnb7ra7jNsUpLGQYiAOwqvQpWYh",
	"Gx0WrOvEGCoWQ86Ma0gRi1WiYq9idHFFTTWzDf8nK8eSHKTkvNQxeZW5jk/fuKpf8KXVDrBWbC3HKFum",
	"kBUTJg9TMRBbjolBiEgkOX9i0lndH5MOkWNRqNACG9354iKqeF484jRZLZrz9QRyisOL6OHAaq+7//dH",
	"U9WMEM62litiuLcGVyYJUcrdtE4BQdM1WHKmtAmFASMivTh7kBNjyZXKt1k9/W73LwPTfPVrgHARuyDi",
	"8cExrsxztLNNETKUdQ2y8XHi2FmBOnHJ05t03rmtHobpvLPsdZqlH68uNavFojZ8+lCJOllr8hqrV+iM",
	"qqoRI5F6cofa4xUiWNZiTnzrDM2u5KDYxlxvwoEtFmjEpj5bK+nZLEaXP81E63fbe9mo+zPieYSRfklj",
	"1DcShFF9z1425JXgHuuO0NTudkdsegH1hhmDM8ZSR7suej+FM1N6KF19SyismUouUOsuWr1Y/sgjMbp/",
	"hUfWbmS/gEfWbzP/eI88TKhNbuHlwvpRY+s7vzEJKkhpSsoU4b9tcaxoidB1isz7YtDpKB6XGecHB91u",
	"t8PNGYus2uy2VmvcdH45/zMAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
