// Package restapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package restapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3FhdcxM7Ev0rXVoeoMqxHSdOgd+SAJts8ZEisPvAZlPtmbZHoJEGSePEpPzft1qasT32mCTUvRT3PlDl",
	"2C2pz+lzWi3uRGLywmjS3onRnXBJRjmGj6+sNdZ1X+mp1HSuPVmNin8orCnIekkhLKVxOZV6YvgPPy9I",
	"jITzVuqpWCw6wtK3UlpKxejzWuhVpw414y+UeLHoiNdSkeueZqX+eoYui3u7xMrCS6PFSFx6KxMPl2fH",
	"e4PhEZzRLXAgzFDJFDkICvScJzw9OoQkQ4uJJ+s6oMwN2QQdQUa3z0RHVIFiJP73Gfcm/b0XV3dHh4sn",
	"orOJoU7sU6EMppfknDQ6ZOk+0LeSnN/mJDHao9TumszkOuHYbTSvFU5B6lQm6KWegpyAQueBFOWkPUgN",
	"GbqMHEgHPqP469NX718/g7AlR/D3E6moC8dKmRsHITHwBsYE/y37/YMEDt/Kk+4K19gYRagZWNx/O7UT",
	"9EkGZrKkOp5XpeMNYOkzY+V36sIpFgWlgB6G+wOQnnIHTwf/lCdwI3Vqbp7x0eFrPueJpYkYiX/0Vqrr",
	"VZLrbdZ/0RE53p7HpcP9QUfkUld/7i/hoLU431JahWy3zFqr6QqjHbWUM/zOnzBNJZOE6qIRcT+uxoEX",
	"lpycakrDyZxVswDH8JXmezNUJUGOBf8rWCOESbYiP4UlWRDVCqm0lHg15yJJ7yAnjyl6BNQpWEpIFt6t",
	"iaGmZYO+CvBD6TN5Lv1pLfMmd1llZVTq/USMPj9SA1eb1Czdz6jNpBL8haWZNKVTcygdpQzfjNmCUFEN",
	"lx596UQAGmjYlv2pnRfeTC0WmUzg7O3xaU3ZOufjeXCdIzsjCxNjwWfSRYtsd48WXYpVCo8ieHe3Wcqz",
	"rV+qORibkqUUlHSeOYsLOPecRcNwcnSe4UjFn7WckPPg+ESdUBfe4m3lbVcWhbEeEAYf5UlsPo9z+E7t",
	"NA0/OBw8f/4Yz/+MaHd7noFdy3Sb1Y8ZQWIJPaXA+74zKcH5y3tLX2/4wPzO9Q8qHvbSmNN2eu8wJ65x",
	"fTO0XWhhuZPfW5Zfyu+N5XzJjOeeXNQALwqF55qzftCLkZDaHx2KUD2Zl7kYDfZfvOgPDgbD4XAY+3b8",
	"flVCqT1NyXI2BVrSvpXr85d1LjEIJkalZMFYSK2c0b2kr/burJG2zsCjyrFLLC4GtWJodBVUag6OUFEK",
	"//rPR/DmK2nAJEwA6KrOUm8GBTrHbrsX51oCDwS0cQVtQdrZJS/neU7cWWKHrDtjnL/qfjk2pQ5dOPRG",
	"V1AiJzKpoYXbKNi12ybPMuR5XVq1w31KkvZ78a6DJRCI6+DThzddeFcqxSMVExqnF1SWMJ0D3UoX70Bd",
	"KoVjRWLkbUn3UbyW1Y8aOC9bTsPS8+7iQqG3sszh1FiC44tz0REzsi5C6nf73T7jNgVpLKQYiYPwVZhS",
	"s1CNHgvW9WIOFYuhZsa1lIjFKlGxVzG6uKKmWtmFf5OVE0kOUnJe6li8ylzHp29cNS/40moHWCu2lmOU",
	"LVPIigmLz1MxEluOiUmISCQ5f2LSeT0fkw6ZY1GoMAIb3fviIqp4X/zEbbLeNBfNAnKJwxfRw4HVQX//",
	"z8+m6hkhnW0tV8TwbA2uTBKilKdpnQKCphuw5ExpEwoBYyK9vHuQC2PJlcp3WT3Dfv8PA9P+9GuBcBmn",
	"IOL44BhX5jna+aYIGUpTg2x8nDp2VqBOXPHyNp33VvNNu9zjc6Vmslj2g08fKiEnjcGutWOFaajqFPF0",
	"qaf3KDw+G4JNLebEL80w4EpOKiNMyXKXCde0uN0rqi6w13Txpkg7azXa7EhXv8xJzQfug7zU/xX5/ISb",
	"fkt31M8ShHH92F5N5ZUCH2ORMM3utkicdgH1hguDPSZSR58uhz6Fc1N6KF39PCismUnuTE0rrb8of2SU",
	"mN3f0yiNt9lvYJTmu+Yvb5THKbfNMrxd2D+KrnnyG5OggpRmpEwR/t8txoqOCPOnyLwvRr2e4rjMOD86",
	"6Pf7PR7TWGTVYXe1eOOhi6vF/wMAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
