// Package restapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package restapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3Fjfbxu5Ef5XBuw9JIAsyYodXPRm+5LGRZwz4qR9SF1jtBxpeeGSPJJrWwn8vxdD7spaaRXbQXu49sGA",
	"RPHHfN9833Dob6KwlbOGTAxi+k2EoqQK08fX3lsfhq/NQhk6NZG8Qc0/OG8d+agoTZM0qxfKzC1/iUtH",
	"YipC9MosxN3dQHj6vVaepJh+Xpt6OWin2tlvVERxNxBvlKYwPClr8+UthjLvHQqvXFTWiKm4iF4VES7e",
	"Hu1NDl/CW7oFngjXqJVEngQOI8cJz14eQFGixyKSDwPQ9oZ8gYGgpNvnYiCaiWIq/vUZ9+bjvVeX314e",
	"3P0kBpsY2sA+OW1RXlAIypoUZfhAv9cU4jYnhTURlQlXZOdXBc/dRvNG4wKUkarAqMwC1Bw0hgikqSIT",
	"QRkoMZQUQAWIJeVfn73+9c1zSFvyDB6fK01DONLa3gRIgUG0MCP4Zz0evyjg4EwdD+9xzazVhIaB5f23",
	"QzvGWJRg5yuq83lNONEC1rG0Xn2lIZygcyQBIxzuT0BFqgI8m/xVHcONMtLePOej0zCf85OnuZiKv4zu",
	"VTdqJDfazP/dQFR4e5qXHu5PBqJSpvm6v4KD3uNyS2kNst0y681mcNYE6kln+p0/oZSKSUJ93pnxMK7O",
	"geeegloYkulkjqqbgCP4Qsu9a9Q1QYWO/xxrhLAo78mXsCILslpBKk9F1EtOkooBKoooMSKgkeCpIOVi",
	"WBNDS8sGfQ3gx9Jnq0rFk1bmXe7Kxsqo9a9zMf38RA1cblKzcj+jtvNG8OeerpWtg15CHUgyfDtjC0JD",
	"NVxEjHUQCWiiYVv2J37pol14dKUq4O3Z0UlL2Trns2VyXSB/TR7m1kMsVcgW2a4ePboU9yE8ieDd1WYl",
	"z756qZdgvSRPErQKkTnLCzj2ikXDcCoMkeEozZ+NmlOIEPhEU9AQzvC28XaonbM+AsLkozrOxedpDt+p",
	"na7hJweTn39+iud/RLS7Pc/ArpTcZvVjSVB4wkgSeN/3VhKc/vJg6tsNHxnfqflOxtNeBivaDu89VsQ5",
	"bm+GvgstLQ/qa8/yC/W1s5wvmdkyUsga4EUp8Zxz1g9GMRXKxJcHImVPVXUlppP9V6/GkxeTw8PDw1y3",
	"8/h9CpWJtCCfcq4qusrDm9GcnZ69hhNrIpm493HpuqE9o+FiCOicTneoNSMn5wNQFS5o5MzieR92h55M",
	"7M3s6S/t9nkSzK2W5MF6kF5d04Mpvt97sJaidb7X0T5JCLtkGvKkXjydeoZaLyEQapLwt398hGi/kAEs",
	"Uu+Boalp7WbgMAT2+YOY1wJ4JKCNy28L0s76fLGsKuKalmtzW5Nz59dW6pmtTar/qSoHR4Waq6KFlu7B",
	"VCiGfeKoU5xXtdc7fK8VKzHfsrACAnkdfPrwbgjva625mWNCc9+E2hPKJdCtCvn2NbXWONMkptHX9BDF",
	"a1F97+rgZas+XEXeXZxrjF7VFZxYT3B0fioG4pp8yJDGw/FwzLitI4NOial4kYZSf1ymbIxYvGGUY2hY",
	"TDmzoSdFLFaFmqsEZpM21DQrh/B38mquKICkEJXJyWuMdnTyLjSdSqy9CYCtYls5ZtkyhayYtPhUiqnY",
	"ckwOQmQiKcRjK5dtZ04mRb5eOH4LGVW+qX7gHlsv13fdBHKK00D2cGJ1Mt7/70fT1IwUzraWG2K4q4dQ",
	"FwWR5D7eSEAwdAOegq19QWnCjMisbj3kxHgKtY5DVs/hePwfA9P/6OyBcJH7L+L5yTGhrir0y00RMpSu",
	"Btn4uAjsrESduOTlfTof3XdW/XLPD6WWSbeqB58+NEIuOi1lb8VKfVhTKfLpyiweUHh+sCSbeqyI37ip",
	"tVYcVEkoyXOVSQ2CuN1zTRXY67p4U6SDtRxtVqTLP8xJ3af1o7w0/iPi+QE3/Snd0T6IEGbtM//+PdAo",
	"8CkWSX30bovkPhvQbLgw2WOuTPbpqqfTuLR1hDq0DxPn7bXiytS10vpb9ntGydH9fxql8yr8Exil+6L6",
	"nzfK05TbZxneLu2fRdc9+Z0tUIOka9LWpf/45bliIFL/KcoY3XQ00jyvtCFOX4zH4xG3aSyy5rBvrXjz",
	"oXeXd/8OAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
