// Package restapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package restapi

// ErrorsEngineInternal defines model for Errors.EngineInternal.
type ErrorsEngineInternal struct {
	Debuginfo string `json:"debuginfo"`
}

// FilesChunkHash Strict SHA-256 Hex Hash validation pattern (64 characters, lowercase hex)
type FilesChunkHash = string

// FilesUploadSessionChunksRequest defines model for Files.UploadSessionChunksRequest.
type FilesUploadSessionChunksRequest struct {
	// ContainsEofChunk Flag indicating if last element in hashes is the last (EOF) chunk in the file. Allows Chunk to be < 4MiB.
	ContainsEofChunk *bool `json:"contains_eof_chunk,omitempty"`

	// Hashes Batch of SHA-256 chunk hashes to authorize. Capped at 512 items (2GiB window).
	Hashes []FilesChunkHash `json:"hashes"`
}

// FilesUploadSessionChunksResponse defines model for Files.UploadSessionChunksResponse.
type FilesUploadSessionChunksResponse struct {
	// Chunks A key-value map mapping each authorized ChunkHash string directly to its metadata and receipts.
	Chunks map[string]FilesUploadSessionPresignedChunk `json:"chunks"`
}

// FilesUploadSessionCommitChunk defines model for Files.UploadSessionCommitChunk.
type FilesUploadSessionCommitChunk struct {
	// Hash SHA-256 Hash of Chunk Previously used to obtain Presign Status
	Hash FilesChunkHash `json:"hash"`

	// Receipt Cryptographic HMAC receipt authorized by the server for this chunk
	Receipt string `json:"receipt"`
}

// FilesUploadSessionCommitRequest defines model for Files.UploadSessionCommitRequest.
type FilesUploadSessionCommitRequest struct {
	// Chunks Strictly ordered list of chunks forming the master file manifest sequence. Max items support a 2TiB file.
	Chunks []FilesUploadSessionCommitChunk `json:"chunks"`
}

// FilesUploadSessionCommitResponse defines model for Files.UploadSessionCommitResponse.
type FilesUploadSessionCommitResponse struct {
	// FileId The created FileNode ID
	FileId string `json:"file_id"`
}

// FilesUploadSessionInitRequest defines model for Files.UploadSessionInitRequest.
type FilesUploadSessionInitRequest struct {
	// FileName Name of the file
	FileName string `json:"file_name"`

	// FileSize Size of the file in bytes. Max size 2TiB.
	FileSize int64 `json:"file_size"`

	// ParentId ID of the parent folder or drive
	ParentId string `json:"parent_id"`
}

// FilesUploadSessionInitResponse defines model for Files.UploadSessionInitResponse.
type FilesUploadSessionInitResponse struct {
	// SessionId Cryptographically sealed JWT token acting as the session_id passport
	SessionId string `json:"session_id"`
}

// FilesUploadSessionPresignedChunk defines model for Files.UploadSessionPresignedChunk.
type FilesUploadSessionPresignedChunk struct {
	// Receipt Symmetric HMAC authorization receipt bound to this specific session and chunk.
	Receipt string `json:"receipt"`

	// UploadUrl The client-direct Presigned upload URL. Null if the chunk already exists.
	UploadUrl *string `json:"upload_url"`
}

// UploadSessionChunksParams defines parameters for UploadSessionChunks.
type UploadSessionChunksParams struct {
	XPlatriumUploadsession string `json:"x-platrium-uploadsession"`
}

// UploadSessionCommitParams defines parameters for UploadSessionCommit.
type UploadSessionCommitParams struct {
	XPlatriumUploadsession string `json:"x-platrium-uploadsession"`
}

// UploadSessionInitializeJSONRequestBody defines body for UploadSessionInitialize for application/json ContentType.
type UploadSessionInitializeJSONRequestBody = FilesUploadSessionInitRequest

// UploadSessionChunksJSONRequestBody defines body for UploadSessionChunks for application/json ContentType.
type UploadSessionChunksJSONRequestBody = FilesUploadSessionChunksRequest

// UploadSessionCommitJSONRequestBody defines body for UploadSessionCommit for application/json ContentType.
type UploadSessionCommitJSONRequestBody = FilesUploadSessionCommitRequest
