// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package eegraphql

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Health string

const (
	HealthOk    Health = "OK"
	HealthNotOk Health = "NOT_OK"
)

var AllHealth = []Health{
	HealthOk,
	HealthNotOk,
}

func (e Health) IsValid() bool {
	switch e {
	case HealthOk, HealthNotOk:
		return true
	}
	return false
}

func (e Health) String() string {
	return string(e)
}

func (e *Health) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Health(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Health", str)
	}
	return nil
}

func (e Health) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Health) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Health) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
