package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"
	"platrium/internal/auth/session"
	"platrium/internal/fsops"
)

// Path is the resolver for the path field.
func (r *fileResolver) Path(ctx context.Context, obj *File) ([]*Folder, error) {
	return r.resolveItemPath(ctx, obj.ID)
}

// Path is the resolver for the path field.
func (r *folderResolver) Path(ctx context.Context, obj *Folder) ([]*Folder, error) {
	return r.resolveItemPath(ctx, obj.ID)
}

// CreateFolder is the resolver for the createFolder field.
func (r *mutationResolver) CreateFolder(ctx context.Context, parentID string, name string) (*Folder, error) {
	panic(fmt.Errorf("not implemented: CreateFolder - createFolder"))
}

// RenameItem is the resolver for the renameItem field.
func (r *mutationResolver) RenameItem(ctx context.Context, id string, newName string) (DriveItem, error) {
	panic(fmt.Errorf("not implemented: RenameItem - renameItem"))
}

// MoveItem is the resolver for the moveItem field.
func (r *mutationResolver) MoveItem(ctx context.Context, id string, newParentID string) (DriveItem, error) {
	panic(fmt.Errorf("not implemented: MoveItem - moveItem"))
}

// DeleteItem is the resolver for the deleteItem field.
func (r *mutationResolver) DeleteItem(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteItem - deleteItem"))
}

// Item is the resolver for the item field.
func (r *queryResolver) Item(ctx context.Context, id string) (DriveItem, error) {
	sess, ok := session.FromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	item, err := r.FSOps.GetItem(ctx, sess.TenantID, id)
	if err != nil {
		return nil, err
	}

	return mapDriveItemRecord(item), nil
}

// FolderContents is the resolver for the folderContents field.
func (r *queryResolver) FolderContents(ctx context.Context, folderID string, first *int, after *string) (*DriveItemConnection, error) {
	sess, ok := session.FromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	limit := 50
	if first != nil && *first > 0 {
		limit = *first
	}

	afterCursor := ""
	if after != nil {
		afterCursor = *after
	}

	// We fetch limit + 1 to determine if there's a next page
	items, err := r.FSOps.GetFolderContents(ctx, sess.TenantID, folderID, limit+1, afterCursor)
	if err != nil {
		return nil, err
	}

	hasNextPage := len(items) > limit
	if hasNextPage {
		items = items[:limit]
	}

	var edges []*DriveItemEdge
	for _, item := range items {
		edges = append(edges, &DriveItemEdge{
			Cursor: item.ID,
			Node:   mapDriveItemRecord(item),
		})
	}

	var endCursor *string
	if len(edges) > 0 {
		c := edges[len(edges)-1].Cursor
		endCursor = &c
	}

	total, err := r.FSOps.GetFolderContentsTotalCount(ctx, sess.TenantID, folderID)
	if err != nil {
		return nil, err
	}

	return &DriveItemConnection{
		Edges: edges,
		PageInfo: &PageInfo{
			HasNextPage: hasNextPage,
			EndCursor:   endCursor,
		},
		TotalCount: total,
	}, nil
}

// Drives is the resolver for the drives field.
func (r *queryResolver) Drives(ctx context.Context) ([]*Folder, error) {
	sess, ok := session.FromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized: missing session context")
	}

	drives, err := r.FSOps.GetUserDrives(ctx, sess.TenantID, sess.UserID)
	if err != nil {
		return nil, err
	}

	var folders []*Folder
	for _, d := range drives {
		driveType := DriveTypePrivate
		if d.Type == fsops.DriveTypeShared {
			driveType = DriveTypeShared
		}

		var quota *int64
		if d.StorageQuota > 0 {
			q := d.StorageQuota
			quota = &q
		}

		folders = append(folders, &Folder{
			ID:   d.ID,
			Name: d.Name,
			Type: DriveItemTypeFolder,
			DriveMetadata: &DriveMetadata{
				DriveType:    driveType,
				StorageUsed:  d.StorageUsed,
				StorageQuota: quota,
			},
			CreatedAt: d.CreatedAt,
			UpdatedAt: d.CreatedAt,
		})
	}

	return folders, nil
}

// File returns FileResolver implementation.
func (r *Resolver) File() FileResolver { return &fileResolver{r} }

// Folder returns FolderResolver implementation.
func (r *Resolver) Folder() FolderResolver { return &folderResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	fileResolver     struct{ *Resolver }
	folderResolver   struct{ *Resolver }
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
