package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"
	"platrium/internal/auth/session"
	"platrium/internal/fsops"
)

// CreateFolder is the resolver for the createFolder field.
func (r *mutationResolver) CreateFolder(ctx context.Context, parentID string, name string) (*Folder, error) {
	panic(fmt.Errorf("not implemented: CreateFolder - createFolder"))
}

// RenameItem is the resolver for the renameItem field.
func (r *mutationResolver) RenameItem(ctx context.Context, id string, newName string) (DriveItem, error) {
	panic(fmt.Errorf("not implemented: RenameItem - renameItem"))
}

// MoveItem is the resolver for the moveItem field.
func (r *mutationResolver) MoveItem(ctx context.Context, id string, newParentID string) (DriveItem, error) {
	panic(fmt.Errorf("not implemented: MoveItem - moveItem"))
}

// DeleteItem is the resolver for the deleteItem field.
func (r *mutationResolver) DeleteItem(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteItem - deleteItem"))
}

// Item is the resolver for the item field.
func (r *queryResolver) Item(ctx context.Context, id string) (DriveItem, error) {
	panic(fmt.Errorf("not implemented: Item - item"))
}

// FolderContents is the resolver for the folderContents field.
func (r *queryResolver) FolderContents(ctx context.Context, folderID string, first *int, after *string) (*DriveItemConnection, error) {
	panic(fmt.Errorf("not implemented: FolderContents - folderContents"))
}

// Drives is the resolver for the drives field.
func (r *queryResolver) Drives(ctx context.Context) ([]*Folder, error) {
	sess, ok := session.FromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized: missing session context")
	}

	drives, err := r.FSOps.GetUserDrives(ctx, sess.TenantID, sess.UserID)
	if err != nil {
		return nil, err
	}

	var folders []*Folder
	for _, d := range drives {
		driveType := DriveTypePrivate
		if d.Type == fsops.DriveTypeShared {
			driveType = DriveTypeShared
		}

		var quota *int64
		if d.StorageQuota > 0 {
			q := d.StorageQuota
			quota = &q
		}

		folders = append(folders, &Folder{
			ID:   d.ID,
			Name: d.Name,
			Type: DriveItemTypeFolder,
			DriveMetadata: &DriveMetadata{
				DriveType:    driveType,
				StorageUsed:  d.StorageUsed,
				StorageQuota: quota,
			},
			CreatedAt: d.CreatedAt,
			UpdatedAt: d.CreatedAt,
		})
	}

	return folders, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
