// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type DriveItem interface {
	IsDriveItem()
	GetID() string
	GetParentID() *string
	GetName() string
	GetType() DriveItemType
	GetCreatedAt() time.Time
	GetUpdatedAt() time.Time
}

type FileItem struct {
	ID        string         `json:"id"`
	ParentID  string         `json:"parentId"`
	Name      string         `json:"name"`
	Type      DriveItemType  `json:"type"`
	Size      int64          `json:"size"`
	MimeType  string         `json:"mimeType"`
	Version   int            `json:"version"`
	Versions  []*FileVersion `json:"versions,omitempty"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
}

func (FileItem) IsDriveItem()                 {}
func (this FileItem) GetID() string           { return this.ID }
func (this FileItem) GetParentID() *string    { return &this.ParentID }
func (this FileItem) GetName() string         { return this.Name }
func (this FileItem) GetType() DriveItemType  { return this.Type }
func (this FileItem) GetCreatedAt() time.Time { return this.CreatedAt }
func (this FileItem) GetUpdatedAt() time.Time { return this.UpdatedAt }

type FileVersion struct {
	Version   int       `json:"version"`
	Size      int64     `json:"size"`
	CreatedAt time.Time `json:"createdAt"`
}

type FolderItem struct {
	ID        string        `json:"id"`
	ParentID  *string       `json:"parentId,omitempty"`
	Name      string        `json:"name"`
	Type      DriveItemType `json:"type"`
	CreatedAt time.Time     `json:"createdAt"`
	UpdatedAt time.Time     `json:"updatedAt"`
}

func (FolderItem) IsDriveItem()                 {}
func (this FolderItem) GetID() string           { return this.ID }
func (this FolderItem) GetParentID() *string    { return this.ParentID }
func (this FolderItem) GetName() string         { return this.Name }
func (this FolderItem) GetType() DriveItemType  { return this.Type }
func (this FolderItem) GetCreatedAt() time.Time { return this.CreatedAt }
func (this FolderItem) GetUpdatedAt() time.Time { return this.UpdatedAt }

type Mutation struct {
}

type Query struct {
}

type DriveItemType string

const (
	DriveItemTypeFile   DriveItemType = "FILE"
	DriveItemTypeFolder DriveItemType = "FOLDER"
)

var AllDriveItemType = []DriveItemType{
	DriveItemTypeFile,
	DriveItemTypeFolder,
}

func (e DriveItemType) IsValid() bool {
	switch e {
	case DriveItemTypeFile, DriveItemTypeFolder:
		return true
	}
	return false
}

func (e DriveItemType) String() string {
	return string(e)
}

func (e *DriveItemType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DriveItemType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DriveItemType", str)
	}
	return nil
}

func (e DriveItemType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DriveItemType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DriveItemType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
