/*
 * Platrium Core API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthLoginRequest {
    #[serde(rename = "idp_id")]
    pub idp_id: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
}

impl AuthLoginRequest {
    pub fn new(idp_id: String, email: String) -> AuthLoginRequest {
        AuthLoginRequest {
            idp_id,
            email,
            password: None,
        }
    }
}

