/*
 * Platrium Core API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthMfaVerifyRequest {
    #[serde(rename = "challenge_token")]
    pub challenge_token: String,
    #[serde(rename = "method")]
    pub method: String,
    #[serde(rename = "code")]
    pub code: String,
}

impl AuthMfaVerifyRequest {
    pub fn new(challenge_token: String, method: String, code: String) -> AuthMfaVerifyRequest {
        AuthMfaVerifyRequest {
            challenge_token,
            method,
            code,
        }
    }
}

