/*
 * Platrium Core API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthTokenRequest {
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "code_verifier")]
    pub code_verifier: String,
}

impl AuthTokenRequest {
    pub fn new(code: String, code_verifier: String) -> AuthTokenRequest {
        AuthTokenRequest {
            code,
            code_verifier,
        }
    }
}

