/*
 * Platrium Core API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthAuthMeResponse {
    #[serde(rename = "user_id")]
    pub user_id: String,
    #[serde(rename = "tenant_id")]
    pub tenant_id: String,
    #[serde(rename = "email")]
    pub email: String,
}

impl AuthAuthMeResponse {
    pub fn new(user_id: String, tenant_id: String, email: String) -> AuthAuthMeResponse {
        AuthAuthMeResponse {
            user_id,
            tenant_id,
            email,
        }
    }
}

