/*
 * Platrium Core API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthAuthorizeRequest {
    /// Where to send the user afterwards: a custom URL scheme, a loopback http URL (127.0.0.1, [::1], localhost, any port), or a configured https universal link.
    #[serde(rename = "redirect_uri")]
    pub redirect_uri: String,
    /// Base64url SHA-256 of the client's secret code_verifier (PKCE S256).
    #[serde(rename = "code_challenge")]
    pub code_challenge: String,
    /// Opaque client value echoed back on the redirect.
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    /// Shown to the user and in the Devices/Apps list, e.g. \"Platrium for iPhone\" or \"Platrium CLI\".
    #[serde(rename = "name")]
    pub name: String,
    /// IOS, MACOS, ANDROID, ... When present the client is registered as a device; when absent it is an app.
    #[serde(rename = "platform", skip_serializing_if = "Option::is_none")]
    pub platform: Option<String>,
    #[serde(rename = "app_version", skip_serializing_if = "Option::is_none")]
    pub app_version: Option<String>,
}

impl AuthAuthorizeRequest {
    pub fn new(redirect_uri: String, code_challenge: String, name: String) -> AuthAuthorizeRequest {
        AuthAuthorizeRequest {
            redirect_uri,
            code_challenge,
            state: None,
            name,
            platform: None,
            app_version: None,
        }
    }
}

