/*
 * Platrium Core API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthClient {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "kind")]
    pub kind: Kind,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "platform", skip_serializing_if = "Option::is_none")]
    pub platform: Option<String>,
    #[serde(rename = "app_version", skip_serializing_if = "Option::is_none")]
    pub app_version: Option<String>,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "last_used_at")]
    pub last_used_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "expires_at", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// True for the credential making this request.
    #[serde(rename = "current")]
    pub current: bool,
}

impl AuthClient {
    pub fn new(id: String, kind: Kind, name: String, created_at: chrono::DateTime<chrono::FixedOffset>, last_used_at: chrono::DateTime<chrono::FixedOffset>, current: bool) -> AuthClient {
        AuthClient {
            id,
            kind,
            name,
            platform: None,
            app_version: None,
            created_at,
            last_used_at,
            expires_at: None,
            current,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Kind {
    #[serde(rename = "DEVICE")]
    Device,
    #[serde(rename = "APP")]
    App,
}

impl Default for Kind {
    fn default() -> Kind {
        Self::Device
    }
}

