/*
 * Platrium Core API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthTokenResponse {
    /// Bearer token. Only shown once.
    #[serde(rename = "token")]
    pub token: String,
    /// Token ID, usable with DELETE /auth/clients/{id}.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "device_id", skip_serializing_if = "Option::is_none")]
    pub device_id: Option<String>,
    #[serde(rename = "expires_at", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl AuthTokenResponse {
    pub fn new(token: String, id: String) -> AuthTokenResponse {
        AuthTokenResponse {
            token,
            id,
            device_id: None,
            expires_at: None,
        }
    }
}

