/*
 * Platrium Core API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthClientListResponse {
    #[serde(rename = "clients")]
    pub clients: Vec<models::AuthClient>,
}

impl AuthClientListResponse {
    pub fn new(clients: Vec<models::AuthClient>) -> AuthClientListResponse {
        AuthClientListResponse {
            clients,
        }
    }
}

