/*
 * Platrium Core API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthLoginResponse {
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "next_step", skip_serializing_if = "Option::is_none")]
    pub next_step: Option<String>,
    #[serde(rename = "challenge_token", skip_serializing_if = "Option::is_none")]
    pub challenge_token: Option<String>,
    #[serde(rename = "available_methods", skip_serializing_if = "Option::is_none")]
    pub available_methods: Option<Vec<String>>,
}

impl AuthLoginResponse {
    pub fn new(status: String) -> AuthLoginResponse {
        AuthLoginResponse {
            status,
            next_step: None,
            challenge_token: None,
            available_methods: None,
        }
    }
}

