/*
 * Platrium Core API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorsMissingChunks {
    #[serde(rename = "missing_chunks")]
    pub missing_chunks: Vec<String>,
}

impl ErrorsMissingChunks {
    pub fn new(missing_chunks: Vec<String>) -> ErrorsMissingChunks {
        ErrorsMissingChunks {
            missing_chunks,
        }
    }
}

