/*
 * Platrium Core API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorsEngineInternal {
    #[serde(rename = "debuginfo")]
    pub debuginfo: String,
}

impl ErrorsEngineInternal {
    pub fn new(debuginfo: String) -> ErrorsEngineInternal {
        ErrorsEngineInternal {
            debuginfo,
        }
    }
}

