/*
 * Platrium Core API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilesUploadSessionPresignedChunk {
    /// The client-direct Presigned upload URL. Null if the chunk already exists.
    #[serde(rename = "upload_url", deserialize_with = "Option::deserialize")]
    pub upload_url: Option<String>,
    /// Symmetric HMAC authorization receipt bound to this specific session and chunk.
    #[serde(rename = "receipt")]
    pub receipt: String,
}

impl FilesUploadSessionPresignedChunk {
    pub fn new(upload_url: Option<String>, receipt: String) -> FilesUploadSessionPresignedChunk {
        FilesUploadSessionPresignedChunk {
            upload_url,
            receipt,
        }
    }
}

