/*
 * Platrium Core API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilesUploadSessionInitRequest {
    /// ID of the parent folder or drive
    #[serde(rename = "parent_id")]
    pub parent_id: String,
    /// Name of the file
    #[serde(rename = "file_name")]
    pub file_name: String,
    /// Size of the file in bytes. Max size 2TiB.
    #[serde(rename = "file_size")]
    pub file_size: i64,
}

impl FilesUploadSessionInitRequest {
    pub fn new(parent_id: String, file_name: String, file_size: i64) -> FilesUploadSessionInitRequest {
        FilesUploadSessionInitRequest {
            parent_id,
            file_name,
            file_size,
        }
    }
}

