/*
 * Platrium Core API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilesDownloadSessionInitRequest {
    /// ID of the file to download
    #[serde(rename = "file_id")]
    pub file_id: String,
    /// Optional file version to target. If not provided, the latest version is used.
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

impl FilesDownloadSessionInitRequest {
    pub fn new(file_id: String) -> FilesDownloadSessionInitRequest {
        FilesDownloadSessionInitRequest {
            file_id,
            version: None,
        }
    }
}

