/*
 * Platrium Core API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilesDownloadSessionChunksRequest {
    /// Batch of chunk indices to request presigned download URLs for. Capped at 512 items.
    #[serde(rename = "indices")]
    pub indices: Vec<i32>,
}

impl FilesDownloadSessionChunksRequest {
    pub fn new(indices: Vec<i32>) -> FilesDownloadSessionChunksRequest {
        FilesDownloadSessionChunksRequest {
            indices,
        }
    }
}

