/*
 * Platrium Core API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilesUploadSessionChunksRequest {
    /// Batch of SHA-256 chunk hashes to authorize. Capped at 500 items (2GB window).
    #[serde(rename = "hashes")]
    pub hashes: Vec<String>,
}

impl FilesUploadSessionChunksRequest {
    pub fn new(hashes: Vec<String>) -> FilesUploadSessionChunksRequest {
        FilesUploadSessionChunksRequest {
            hashes,
        }
    }
}

