/*
 * Platrium Core API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilesDownloadSessionInitResponse {
    /// Cryptographically sealed JWT token acting as the download passport
    #[serde(rename = "session_id")]
    pub session_id: String,
    /// Name of the file
    #[serde(rename = "file_name")]
    pub file_name: String,
    /// Total size of the file in bytes
    #[serde(rename = "file_size")]
    pub file_size: i64,
    /// MIME Content-Type of the file
    #[serde(rename = "mime_type")]
    pub mime_type: String,
}

impl FilesDownloadSessionInitResponse {
    pub fn new(session_id: String, file_name: String, file_size: i64, mime_type: String) -> FilesDownloadSessionInitResponse {
        FilesDownloadSessionInitResponse {
            session_id,
            file_name,
            file_size,
            mime_type,
        }
    }
}

