/*
 * Platrium Core API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilesCreateFileRequest {
    /// ID of the parent folder or drive
    #[serde(rename = "parent_id")]
    pub parent_id: String,
    /// Name of the file
    #[serde(rename = "file_name")]
    pub file_name: String,
    /// Array of chunk hashes
    #[serde(rename = "hashes")]
    pub hashes: Vec<String>,
}

impl FilesCreateFileRequest {
    pub fn new(parent_id: String, file_name: String, hashes: Vec<String>) -> FilesCreateFileRequest {
        FilesCreateFileRequest {
            parent_id,
            file_name,
            hashes,
        }
    }
}

