/*
 * Platrium Core API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilesCreateFileResponse {
    #[serde(rename = "file_id")]
    pub file_id: String,
}

impl FilesCreateFileResponse {
    pub fn new(file_id: String) -> FilesCreateFileResponse {
        FilesCreateFileResponse {
            file_id,
        }
    }
}

