/*
 * Platrium Core API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilesUploadSessionInitResponse {
    /// Cryptographically sealed JWT token acting as the session_id passport
    #[serde(rename = "session_id")]
    pub session_id: String,
}

impl FilesUploadSessionInitResponse {
    pub fn new(session_id: String) -> FilesUploadSessionInitResponse {
        FilesUploadSessionInitResponse {
            session_id,
        }
    }
}

