/*
 * Platrium Core API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilesUploadSessionChunksResponse {
    /// A key-value map mapping each authorized ChunkHash string directly to its metadata and receipts.
    #[serde(rename = "chunks")]
    pub chunks: std::collections::HashMap<String, models::FilesChunkUploadInfo>,
}

impl FilesUploadSessionChunksResponse {
    pub fn new(chunks: std::collections::HashMap<String, models::FilesChunkUploadInfo>) -> FilesUploadSessionChunksResponse {
        FilesUploadSessionChunksResponse {
            chunks,
        }
    }
}

