/*
 * Platrium Core API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilesUploadSessionCommitRequest {
    /// Strictly ordered list of chunks forming the master file manifest sequence. Max items support a 2TiB file.
    #[serde(rename = "chunks")]
    pub chunks: Vec<models::FilesUploadSessionCommitChunk>,
}

impl FilesUploadSessionCommitRequest {
    pub fn new(chunks: Vec<models::FilesUploadSessionCommitChunk>) -> FilesUploadSessionCommitRequest {
        FilesUploadSessionCommitRequest {
            chunks,
        }
    }
}

