package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"platrium/internal/auth/actor"
	"platrium/internal/authz"
	"platrium/internal/identity"
	"platrium/internal/orchestrator"
)

// CreateLocalUser is the resolver for the createLocalUser field.
func (r *mutationResolver) CreateLocalUser(ctx context.Context, input CreateLocalUserInput) (*AdminUser, error) {
	p, err := actor.Principal(ctx, r.Authz)
	if err != nil {
		return nil, err
	}
	in := orchestrator.CreateLocalUserInput{Email: input.Email, DisplayName: input.DisplayName, Password: input.Password}
	if input.Role != nil {
		in.Role = *input.Role
	}
	u, err := r.UserAdmin.CreateLocalUser(ctx, p, in)
	if err != nil {
		return nil, err
	}
	return mapAdminUser(u), nil
}

// UpdateLocalUser is the resolver for the updateLocalUser field.
func (r *mutationResolver) UpdateLocalUser(ctx context.Context, id string, input UpdateLocalUserInput) (*AdminUser, error) {
	p, err := actor.Principal(ctx, r.Authz)
	if err != nil {
		return nil, err
	}
	u, err := r.UserAdmin.UpdateLocalUser(ctx, p, id, input.DisplayName, input.Role)
	if err != nil {
		return nil, err
	}
	return mapAdminUser(u), nil
}

// ResetLocalUserPassword is the resolver for the resetLocalUserPassword field.
func (r *mutationResolver) ResetLocalUserPassword(ctx context.Context, id string, password string) (bool, error) {
	p, err := actor.Principal(ctx, r.Authz)
	if err != nil {
		return false, err
	}
	if err := r.UserAdmin.ResetLocalUserPassword(ctx, p, id, password); err != nil {
		return false, err
	}
	return true, nil
}

// SetUserDisabled is the resolver for the setUserDisabled field.
func (r *mutationResolver) SetUserDisabled(ctx context.Context, id string, disabled bool) (*AdminUser, error) {
	p, err := actor.Principal(ctx, r.Authz)
	if err != nil {
		return nil, err
	}
	u, err := r.UserAdmin.SetUserDisabled(ctx, p, id, disabled)
	if err != nil {
		return nil, err
	}
	return mapAdminUser(u), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*Me, error) {
	p, err := actor.Principal(ctx, r.Authz)
	if err != nil {
		return nil, err
	}
	users, err := r.UserStore.GetByIDs(ctx, p.TenantID, []string{p.UserID})
	if err != nil {
		return nil, err
	}
	u, ok := users[p.UserID]
	if !ok {
		return nil, actor.ErrUnauthenticated
	}
	perms, native, err := r.UserStore.Access(ctx, p.TenantID, p.UserID)
	if err != nil {
		return nil, err
	}

	me := &Me{
		UserID:          u.ID,
		TenantID:        u.TenantID,
		Email:           u.Email,
		DisplayName:     u.DisplayName,
		Role:            u.Role,
		Permissions:     perms.Sorted(),
		AssignableRoles: []string{},
	}
	for _, role := range authz.TenantRoles() {
		if authz.CanAssignRole(perms, role, native) {
			me.AssignableRoles = append(me.AssignableRoles, role)
		}
	}
	return me, nil
}

// AdminUsers is the resolver for the adminUsers field.
func (r *queryResolver) AdminUsers(ctx context.Context, first *int, after *string, search *string, sourceID *string, status *UserStatus) (*AdminUserConnection, error) {
	p, err := actor.Principal(ctx, r.Authz)
	if err != nil {
		return nil, err
	}

	limit := defaultAdminPage
	if first != nil && *first > 0 {
		limit = min(*first, maxAdminPage)
	}
	cursor, err := decodeUserCursor(after)
	if err != nil {
		return nil, err
	}
	f := identity.UserFilter{}
	if search != nil {
		f.Search = *search
	}
	if sourceID != nil {
		f.IdpID = *sourceID
	}
	if status != nil {
		f.Status = identity.UserStatus(*status)
	}

	items, hasNext, total, err := r.UserAdmin.ListUsers(ctx, p, f, cursor, limit)
	if err != nil {
		return nil, err
	}

	conn := &AdminUserConnection{Edges: make([]*AdminUserEdge, 0, len(items)), PageInfo: &PageInfo{HasNextPage: hasNext}, TotalCount: total}
	for _, it := range items {
		conn.Edges = append(conn.Edges, &AdminUserEdge{Cursor: encodeUserCursor(it), Node: mapAdminUser(it)})
	}
	if n := len(conn.Edges); n > 0 {
		end := conn.Edges[n-1].Cursor
		conn.PageInfo.EndCursor = &end
	}
	return conn, nil
}

// AdminIdentitySources is the resolver for the adminIdentitySources field.
func (r *queryResolver) AdminIdentitySources(ctx context.Context) ([]*IdentitySource, error) {
	p, err := actor.Principal(ctx, r.Authz)
	if err != nil {
		return nil, err
	}
	idps, err := r.UserAdmin.IdentitySources(ctx, p)
	if err != nil {
		return nil, err
	}
	out := make([]*IdentitySource, 0, len(idps))
	for _, i := range idps {
		out = append(out, &IdentitySource{ID: i.ID, Name: i.Name, Type: i.Type, IsLocal: i.Type == "LOCAL"})
	}
	return out, nil
}
