package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
)

// CreateSharedDrive is the resolver for the createSharedDrive field.
func (r *mutationResolver) CreateSharedDrive(ctx context.Context, name string) (*Folder, error) {
	p, err := r.Actors.Principal(ctx)
	if err != nil {
		return nil, err
	}
	d, err := r.DriveOrch.CreateSharedDrive(ctx, p, name)
	if err != nil {
		return nil, err
	}
	return mapDrive(d), nil
}

// SetSharedDriveCreators is the resolver for the setSharedDriveCreators field.
func (r *mutationResolver) SetSharedDriveCreators(ctx context.Context, groupIds []string) ([]*DirectorySubject, error) {
	p, err := r.Actors.Principal(ctx)
	if err != nil {
		return nil, err
	}
	if err := r.DriveOrch.SetSharedDriveCreators(ctx, p, groupIds); err != nil {
		return nil, err
	}
	return r.creatorGroups(ctx, p)
}

// CanCreateSharedDrive is the resolver for the canCreateSharedDrive field.
func (r *queryResolver) CanCreateSharedDrive(ctx context.Context) (bool, error) {
	p, err := r.Actors.Principal(ctx)
	if err != nil {
		return false, err
	}
	return r.DriveOrch.CanCreateSharedDrive(ctx, p)
}

// SharedDriveCreators is the resolver for the sharedDriveCreators field.
func (r *queryResolver) SharedDriveCreators(ctx context.Context) ([]*DirectorySubject, error) {
	p, err := r.Actors.Principal(ctx)
	if err != nil {
		return nil, err
	}
	return r.creatorGroups(ctx, p)
}
