package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"platrium/internal/auth/actor"
	"platrium/internal/authz"
)

// CreateSharedDrive is the resolver for the createSharedDrive field.
func (r *mutationResolver) CreateSharedDrive(ctx context.Context, name string) (*Folder, error) {
	p, err := actor.Principal(ctx, r.Authz)
	if err != nil {
		return nil, err
	}
	d, err := r.DriveOrch.CreateSharedDrive(ctx, p, name)
	if err != nil {
		return nil, err
	}
	return mapDrive(d), nil
}

// SetSharedDriveCreators is the resolver for the setSharedDriveCreators field.
func (r *mutationResolver) SetSharedDriveCreators(ctx context.Context, groupIds []string) ([]*DirectorySubject, error) {
	p, err := actor.Principal(ctx, r.Authz)
	if err != nil {
		return nil, err
	}
	if err := r.DriveOrch.SetSharedDriveCreators(ctx, p, groupIds); err != nil {
		return nil, err
	}
	return r.creatorGroups(ctx, p)
}

// CanCreateSharedDrive is the resolver for the canCreateSharedDrive field.
func (r *queryResolver) CanCreateSharedDrive(ctx context.Context) (bool, error) {
	p, err := actor.Principal(ctx, r.Authz)
	if err != nil {
		return false, err
	}
	return r.DriveOrch.CanCreateSharedDrive(ctx, p)
}

// SharedDriveCreators is the resolver for the sharedDriveCreators field.
func (r *queryResolver) SharedDriveCreators(ctx context.Context) ([]*DirectorySubject, error) {
	p, err := actor.Principal(ctx, r.Authz)
	if err != nil {
		return nil, err
	}
	return r.creatorGroups(ctx, p)
}

// creatorGroups lists the groups allowed to create shared drives, with names.
func (r *Resolver) creatorGroups(ctx context.Context, p authz.Principal) ([]*DirectorySubject, error) {
	ids, err := r.DriveOrch.SharedDriveCreators(ctx, p)
	if err != nil {
		return nil, err
	}
	groups, err := r.GroupStore.GetByIDs(ctx, p.TenantID, ids)
	if err != nil {
		return nil, err
	}
	out := make([]*DirectorySubject, 0, len(ids))
	for _, id := range ids {
		if g, ok := groups[id]; ok {
			out = append(out, &DirectorySubject{Type: string(authz.SubjectGroup), ID: g.ID, Name: g.Name})
		}
	}
	return out, nil
}
