package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"
	"platrium/internal/auth/actor"
	"platrium/internal/auth/session"
	"platrium/internal/fsops"
	"platrium/internal/notifications/events"
	"time"
)

// Path is the resolver for the path field.
func (r *fileResolver) Path(ctx context.Context, obj *File) ([]*Folder, error) {
	return r.resolveItemPath(ctx, obj.ID)
}

// Path is the resolver for the path field.
func (r *folderResolver) Path(ctx context.Context, obj *Folder) ([]*Folder, error) {
	return r.resolveItemPath(ctx, obj.ID)
}

// CreateFolder is the resolver for the createFolder field.
func (r *mutationResolver) CreateFolder(ctx context.Context, parentID string, name string) (*Folder, error) {
	p, err := actor.Principal(ctx, r.Authz)
	if err != nil {
		return nil, err
	}

	folder, err := r.FSOps.CreateFolder(ctx, p, parentID, name)
	if err != nil {
		return nil, err
	}

	res := mapFolderRecord(folder)
	r.Broker.Publish(ctx, []string{p.UserID}, events.DriveEvent{
		EventType: events.EventUpdated,
		ItemID:    res.ID,
		ParentID:  res.ParentID,
		Timestamp: time.Now(),
	})

	return res, nil
}

// RenameItem is the resolver for the renameItem field.
func (r *mutationResolver) RenameItem(ctx context.Context, id string, newName string) (DriveItem, error) {
	p, err := actor.Principal(ctx, r.Authz)
	if err != nil {
		return nil, err
	}

	item, err := r.FSOps.RenameItem(ctx, p, id, newName)
	if err != nil {
		return nil, err
	}

	res := mapDriveItemRecord(item)
	r.Broker.Publish(ctx, []string{p.UserID}, events.DriveEvent{
		EventType: events.EventUpdated,
		ItemID:    id,
		ParentID:  res.GetParentID(),
		Timestamp: time.Now(),
	})

	return res, nil
}

// MoveItem is the resolver for the moveItem field.
func (r *mutationResolver) MoveItem(ctx context.Context, id string, newParentID string) (DriveItem, error) {
	p, err := actor.Principal(ctx, r.Authz)
	if err != nil {
		return nil, err
	}

	item, err := r.FSOps.MoveItem(ctx, p, id, newParentID)
	if err != nil {
		return nil, err
	}

	res := mapDriveItemRecord(item)
	r.Broker.Publish(ctx, []string{p.UserID}, events.DriveEvent{
		EventType: events.EventUpdated,
		ItemID:    id,
		ParentID:  res.GetParentID(),
		Timestamp: time.Now(),
	})

	return res, nil
}

// CopyFile is the resolver for the copyFile field.
func (r *mutationResolver) CopyFile(ctx context.Context, fileID string, newParentID string, newName string) (*File, error) {
	p, err := actor.Principal(ctx, r.Authz)
	if err != nil {
		return nil, err
	}

	file, err := r.FSOps.CopyFile(ctx, p, fileID, newParentID, newName)
	if err != nil {
		return nil, err
	}

	res := mapFileRecord(file)
	r.Broker.Publish(ctx, []string{p.UserID}, events.DriveEvent{
		EventType: events.EventUpdated,
		ItemID:    res.ID,
		ParentID:  &res.ParentID,
		Timestamp: time.Now(),
	})

	return res, nil
}

// DeleteItem is the resolver for the deleteItem field.
func (r *mutationResolver) DeleteItem(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteItem - deleteItem"))
}

// Item is the resolver for the item field.
func (r *queryResolver) Item(ctx context.Context, id string) (DriveItem, error) {
	p, err := actor.Principal(ctx, r.Authz)
	if err != nil {
		return nil, err
	}

	item, err := r.FSOps.GetItem(ctx, p, id)
	if err != nil {
		return nil, err
	}

	return mapDriveItemRecord(item), nil
}

// FolderContents is the resolver for the folderContents field.
func (r *queryResolver) FolderContents(ctx context.Context, folderID string, first *int, after *string) (*DriveItemConnection, error) {
	p, err := actor.Principal(ctx, r.Authz)
	if err != nil {
		return nil, err
	}

	limit := 50
	if first != nil && *first > 0 {
		limit = *first
	}

	afterCursor := ""
	if after != nil {
		afterCursor = *after
	}

	// We fetch limit + 1 to determine if there's a next page
	items, err := r.FSOps.GetFolderContents(ctx, p, folderID, limit+1, afterCursor)
	if err != nil {
		return nil, err
	}

	hasNextPage := len(items) > limit
	if hasNextPage {
		items = items[:limit]
	}

	var edges []*DriveItemEdge
	for _, item := range items {
		edges = append(edges, &DriveItemEdge{
			Cursor: item.ID,
			Node:   mapDriveItemRecord(item),
		})
	}

	var endCursor *string
	if len(edges) > 0 {
		c := edges[len(edges)-1].Cursor
		endCursor = &c
	}

	total, err := r.FSOps.GetFolderContentsTotalCount(ctx, p, folderID)
	if err != nil {
		return nil, err
	}

	return &DriveItemConnection{
		Edges: edges,
		PageInfo: &PageInfo{
			HasNextPage: hasNextPage,
			EndCursor:   endCursor,
		},
		TotalCount: total,
	}, nil
}

// Drives is the resolver for the drives field.
func (r *queryResolver) Drives(ctx context.Context) ([]*Folder, error) {
	p, err := actor.Principal(ctx, r.Authz)
	if err != nil {
		return nil, err
	}

	drives, err := r.FSOps.GetUserDrives(ctx, p)
	if err != nil {
		return nil, err
	}

	var folders []*Folder
	for _, d := range drives {
		driveType := DriveTypePrivate
		if d.Type == fsops.DriveTypeShared {
			driveType = DriveTypeShared
		}

		var quota *int64
		if d.StorageQuota > 0 {
			q := d.StorageQuota
			quota = &q
		}

		folders = append(folders, &Folder{
			ID:   d.ID,
			Name: d.Name,
			Type: DriveItemTypeFolder,
			DriveMetadata: &DriveMetadata{
				DriveType:    driveType,
				StorageUsed:  d.StorageUsed,
				StorageQuota: quota,
			},
			CreatedAt: d.CreatedAt,
			UpdatedAt: d.CreatedAt,
		})
	}

	return folders, nil
}

// GetChanges is the resolver for the getChanges field.
func (r *queryResolver) GetChanges(ctx context.Context, folderID string, since time.Time) ([]*DriveItemEvent, error) {
	p, err := actor.Principal(ctx, r.Authz)
	if err != nil {
		return nil, err
	}

	changes, err := r.FSOps.GetFolderChanges(ctx, p, folderID, since)
	if err != nil {
		return nil, err
	}

	var events []*DriveItemEvent
	for _, item := range changes {
		events = append(events, &DriveItemEvent{
			EventType: DriveItemEventTypeUpdated,
			Item:      mapDriveItemRecord(item),
		})
	}

	return events, nil
}

// DriveItemChanged is the resolver for the driveItemChanged field.
func (r *subscriptionResolver) DriveItemChanged(ctx context.Context) (<-chan *DriveItemEvent, error) {
	sess, ok := session.FromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	// Subscribe to GraphQL WebSocket transport for the active User
	ch, unsub := r.SubsManager.Subscribe(sess.UserID)

	// Unsubscribe when connection closes
	go func() {
		<-ctx.Done()
		unsub()
	}()

	return ch, nil
}

// File returns FileResolver implementation.
func (r *Resolver) File() FileResolver { return &fileResolver{r} }

// Folder returns FolderResolver implementation.
func (r *Resolver) Folder() FolderResolver { return &folderResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type (
	fileResolver         struct{ *Resolver }
	folderResolver       struct{ *Resolver }
	mutationResolver     struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
