package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"
	"platrium/internal/auth"
	"platrium/internal/authz"
	"platrium/internal/orchestrator"
)

// CreateIdentityProvider is the resolver for the createIdentityProvider field.
func (r *mutationResolver) CreateIdentityProvider(ctx context.Context, input CreateIdentityProviderInput) (*IdentityProvider, error) {
	p, err := r.Actors.Principal(ctx)
	if err != nil {
		return nil, err
	}
	policy := auth.ProvisioningPolicy{JITUsers: input.JitUsers, DefaultRole: input.DefaultRole, AllowedEmailDomains: input.AllowedEmailDomains}

	var m *orchestrator.ManagedIdp
	switch {
	case input.Config.Oidc != nil:
		cfg, err := oidcConfigFromInput(input.Config.Oidc)
		if err != nil {
			return nil, err
		}
		m, err = r.IdpAdmin.CreateOIDC(ctx, p, input.Name, policy, cfg)
		if err != nil {
			return nil, err
		}
	default:
		return nil, fmt.Errorf("%w: no provider configuration given", authz.ErrInvalid)
	}
	return mapIdentityProvider(m), nil
}

// UpdateIdentityProvider is the resolver for the updateIdentityProvider field.
func (r *mutationResolver) UpdateIdentityProvider(ctx context.Context, id string, input UpdateIdentityProviderInput) (*IdentityProvider, error) {
	p, err := r.Actors.Principal(ctx)
	if err != nil {
		return nil, err
	}
	in := auth.UpdateIdpParams{Name: input.Name, JITUsers: input.JitUsers, DefaultRole: input.DefaultRole}
	if input.AllowedEmailDomains != nil {
		in.AllowedEmailDomains = &input.AllowedEmailDomains
	}
	m, err := r.IdpAdmin.Update(ctx, p, id, in)
	if err != nil {
		return nil, err
	}
	return mapIdentityProvider(m), nil
}

// UpdateOidcConfig is the resolver for the updateOidcConfig field.
func (r *mutationResolver) UpdateOidcConfig(ctx context.Context, id string, input UpdateOidcConfigInput) (*IdentityProvider, error) {
	p, err := r.Actors.Principal(ctx)
	if err != nil {
		return nil, err
	}
	in, err := oidcUpdateFromInput(input)
	if err != nil {
		return nil, err
	}
	m, err := r.IdpAdmin.UpdateOIDC(ctx, p, id, in)
	if err != nil {
		return nil, err
	}
	return mapIdentityProvider(m), nil
}

// SetIdentityProviderEnabled is the resolver for the setIdentityProviderEnabled field.
func (r *mutationResolver) SetIdentityProviderEnabled(ctx context.Context, id string, enabled bool) (*IdentityProvider, error) {
	p, err := r.Actors.Principal(ctx)
	if err != nil {
		return nil, err
	}
	m, err := r.IdpAdmin.SetEnabled(ctx, p, id, enabled)
	if err != nil {
		return nil, err
	}
	return mapIdentityProvider(m), nil
}

// DeleteIdentityProvider is the resolver for the deleteIdentityProvider field.
func (r *mutationResolver) DeleteIdentityProvider(ctx context.Context, id string) (bool, error) {
	p, err := r.Actors.Principal(ctx)
	if err != nil {
		return false, err
	}
	if err := r.IdpAdmin.Delete(ctx, p, id); err != nil {
		return false, err
	}
	return true, nil
}

// TestOidcDiscovery is the resolver for the testOidcDiscovery field.
func (r *mutationResolver) TestOidcDiscovery(ctx context.Context, issuer string) (*OidcDiscoveryResult, error) {
	p, err := r.Actors.Principal(ctx)
	if err != nil {
		return nil, err
	}
	return mapDiscovery(r.IdpAdmin.CheckOIDC(ctx, p, issuer))
}

// IdentityProviders is the resolver for the identityProviders field.
func (r *queryResolver) IdentityProviders(ctx context.Context) ([]*IdentityProvider, error) {
	p, err := r.Actors.Principal(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := r.IdpAdmin.List(ctx, p)
	if err != nil {
		return nil, err
	}
	out := make([]*IdentityProvider, 0, len(rows))
	for _, m := range rows {
		out = append(out, mapIdentityProvider(m))
	}
	return out, nil
}

// IdentityProvider is the resolver for the identityProvider field.
func (r *queryResolver) IdentityProvider(ctx context.Context, id string) (*IdentityProvider, error) {
	p, err := r.Actors.Principal(ctx)
	if err != nil {
		return nil, err
	}
	m, err := r.IdpAdmin.Get(ctx, p, id)
	if err != nil {
		return nil, err
	}
	return mapIdentityProvider(m), nil
}
