package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"

	"platrium/internal/auth/actor"
	"platrium/internal/authz"
	"platrium/internal/identity"
)

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*Me, error) {
	c, err := r.Actors.Identity(ctx)
	if err != nil {
		return nil, err
	}
	u, err := r.UserStore.Get(ctx, c.TenantID, c.UserID)
	if errors.Is(err, identity.ErrNotFound) {
		return nil, actor.ErrUnauthenticated
	}
	if err != nil {
		return nil, err
	}

	me := &Me{
		UserID:          u.ID,
		TenantID:        u.TenantID,
		Email:           u.Email,
		DisplayName:     u.DisplayName,
		Role:            u.Role,
		Permissions:     c.Perms.Sorted(),
		AssignableRoles: []string{},
	}
	for _, role := range authz.TenantRoles() {
		if authz.CanAssignRole(c.Perms, role, c.Native) {
			me.AssignableRoles = append(me.AssignableRoles, role)
		}
	}
	return me, nil
}
