package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"
)

// ServerInfo is the resolver for the serverInfo field.
func (r *queryResolver) ServerInfo(ctx context.Context) (*ServerInfo, error) {
	panic(fmt.Errorf("not implemented: ServerInfo - serverInfo"))
}
