package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"strings"

	"platrium/internal/auth/actor"
	"platrium/internal/authz"
)

// ShareItem is the resolver for the shareItem field.
func (r *mutationResolver) ShareItem(ctx context.Context, input ShareInput) (*AccessGrant, error) {
	p, err := actor.Principal(ctx, r.Authz)
	if err != nil {
		return nil, err
	}
	role, err := parseRole(input.Role)
	if err != nil {
		return nil, err
	}

	g, err := r.Authz.Grant(ctx, p, authz.GrantInput{
		ItemID:     input.ItemID,
		Subject:    authz.Subject{Type: authz.SubjectType(strings.ToUpper(input.SubjectType)), ID: input.SubjectID},
		Role:       role,
		NoDownload: input.NoDownload != nil && *input.NoDownload,
		ExpiresAt:  input.ExpiresAt,
	})
	if err != nil {
		return nil, err
	}

	names, err := r.subjectNames(ctx, p.TenantID, []authz.Grant{*g})
	if err != nil {
		return nil, err
	}
	return mapGrant(*g, names), nil
}

// RevokeAccess is the resolver for the revokeAccess field.
func (r *mutationResolver) RevokeAccess(ctx context.Context, grantID string) (bool, error) {
	p, err := actor.Principal(ctx, r.Authz)
	if err != nil {
		return false, err
	}
	if err := r.Authz.Revoke(ctx, p, grantID); err != nil {
		return false, err
	}
	return true, nil
}

// SetGeneralAccess is the resolver for the setGeneralAccess field.
func (r *mutationResolver) SetGeneralAccess(ctx context.Context, input GeneralAccessInput) (*GeneralAccess, error) {
	p, err := actor.Principal(ctx, r.Authz)
	if err != nil {
		return nil, err
	}

	in := authz.GeneralAccessInput{
		ItemID:     input.ItemID,
		Level:      authz.GeneralAccessLevel(strings.ToUpper(input.Level)),
		NoDownload: input.NoDownload != nil && *input.NoDownload,
		ExpiresAt:  input.ExpiresAt,
	}
	if input.Role != nil && *input.Role != "" {
		role, err := parseRole(*input.Role)
		if err != nil {
			return nil, err
		}
		in.Role = role
	}
	if err := r.Authz.SetGeneralAccess(ctx, p, in); err != nil {
		return nil, err
	}

	access, err := r.Authz.ItemAccess(ctx, p, input.ItemID)
	if err != nil {
		return nil, err
	}
	level, g := authz.GeneralAccessOf(access.Grants)
	return mapGeneralAccess(level, g), nil
}

// SetInheritance is the resolver for the setInheritance field.
func (r *mutationResolver) SetInheritance(ctx context.Context, itemID string, inherit bool) (bool, error) {
	p, err := actor.Principal(ctx, r.Authz)
	if err != nil {
		return false, err
	}
	if err := r.Authz.SetInheritance(ctx, p, itemID, inherit); err != nil {
		return false, err
	}
	return true, nil
}

// ItemAccess is the resolver for the itemAccess field.
func (r *queryResolver) ItemAccess(ctx context.Context, itemID string) (*ItemAccess, error) {
	p, err := actor.Principal(ctx, r.Authz)
	if err != nil {
		return nil, err
	}
	access, err := r.Authz.ItemAccess(ctx, p, itemID)
	if err != nil {
		return nil, err
	}
	names, err := r.subjectNames(ctx, p.TenantID, access.Grants)
	if err != nil {
		return nil, err
	}

	level, general := authz.GeneralAccessOf(access.Grants)
	out := &ItemAccess{
		ItemID:              itemID,
		InheritsPermissions: access.InheritsPermissions,
		GeneralAccess:       mapGeneralAccess(level, general),
		Grants:              []*AccessGrant{},
	}
	for _, g := range access.Grants {
		// General access is reported on its own, above the named grants.
		if g.Subject.Type == authz.SubjectTenant || g.Subject.Type == authz.SubjectPublic {
			continue
		}
		out.Grants = append(out.Grants, mapGrant(g, names))
	}
	return out, nil
}

// SharedWithMe is the resolver for the sharedWithMe field.
func (r *queryResolver) SharedWithMe(ctx context.Context, first *int, after *string) (*SharedItemConnection, error) {
	p, err := actor.Principal(ctx, r.Authz)
	if err != nil {
		return nil, err
	}

	limit := 50
	if first != nil && *first > 0 {
		limit = min(*first, maxSharedPage)
	}
	cursor := ""
	if after != nil {
		cursor = *after
	}

	// Ask for one more than the page to learn whether another page exists.
	shared, err := r.Authz.SharedWithMe(ctx, p, limit+1, cursor)
	if err != nil {
		return nil, err
	}
	hasNext := len(shared) > limit
	if hasNext {
		shared = shared[:limit]
	}

	ids := make([]string, len(shared))
	for i, s := range shared {
		ids[i] = s.ItemID
	}
	records, err := r.FSOps.GetItems(ctx, p, ids)
	if err != nil {
		return nil, err
	}
	byID := make(map[string]DriveItem, len(records))
	for _, rec := range records {
		byID[rec.ID] = mapDriveItemRecord(rec)
	}

	edges := make([]*SharedItemEdge, 0, len(shared))
	for _, s := range shared {
		node, ok := byID[s.ItemID]
		if !ok {
			continue // no longer visible
		}
		edges = append(edges, &SharedItemEdge{
			Cursor: s.ItemID,
			Node: &SharedItem{
				Item:         node,
				Role:         string(s.Role),
				Capabilities: s.Caps.Verbs(),
			},
		})
	}

	page := &PageInfo{HasNextPage: hasNext}
	if len(shared) > 0 {
		end := shared[len(shared)-1].ItemID
		page.EndCursor = &end
	}
	return &SharedItemConnection{Edges: edges, PageInfo: page}, nil
}
