// Code generated by ent, DO NOT EDIT.

package ent

import (
	"platrium/internal/infra/db/ent/device"
	"platrium/internal/infra/db/ent/domain"
	"platrium/internal/infra/db/ent/drive"
	"platrium/internal/infra/db/ent/driveitem"
	"platrium/internal/infra/db/ent/group"
	"platrium/internal/infra/db/ent/idpprovider"
	"platrium/internal/infra/db/ent/tenant"
	"platrium/internal/infra/db/ent/user"
	"platrium/internal/infra/db/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	deviceMixin := schema.Device{}.Mixin()
	deviceMixinFields0 := deviceMixin[0].Fields()
	_ = deviceMixinFields0
	deviceMixinFields1 := deviceMixin[1].Fields()
	_ = deviceMixinFields1
	deviceFields := schema.Device{}.Fields()
	_ = deviceFields
	// deviceDescCreatedAt is the schema descriptor for created_at field.
	deviceDescCreatedAt := deviceMixinFields1[0].Descriptor()
	// device.DefaultCreatedAt holds the default value on creation for the created_at field.
	device.DefaultCreatedAt = deviceDescCreatedAt.Default.(func() time.Time)
	// deviceDescUpdatedAt is the schema descriptor for updated_at field.
	deviceDescUpdatedAt := deviceMixinFields1[1].Descriptor()
	// device.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	device.DefaultUpdatedAt = deviceDescUpdatedAt.Default.(func() time.Time)
	// device.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	device.UpdateDefaultUpdatedAt = deviceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// deviceDescTenantID is the schema descriptor for tenant_id field.
	deviceDescTenantID := deviceFields[0].Descriptor()
	// device.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	device.TenantIDValidator = deviceDescTenantID.Validators[0].(func(string) error)
	// deviceDescUserID is the schema descriptor for user_id field.
	deviceDescUserID := deviceFields[1].Descriptor()
	// device.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	device.UserIDValidator = deviceDescUserID.Validators[0].(func(string) error)
	// deviceDescTransportType is the schema descriptor for transport_type field.
	deviceDescTransportType := deviceFields[2].Descriptor()
	// device.TransportTypeValidator is a validator for the "transport_type" field. It is called by the builders before save.
	device.TransportTypeValidator = func() func(string) error {
		validators := deviceDescTransportType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(transport_type string) error {
			for _, fn := range fns {
				if err := fn(transport_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// deviceDescID is the schema descriptor for id field.
	deviceDescID := deviceMixinFields0[0].Descriptor()
	// device.DefaultID holds the default value on creation for the id field.
	device.DefaultID = deviceDescID.Default.(func() string)
	// device.IDValidator is a validator for the "id" field. It is called by the builders before save.
	device.IDValidator = func() func(string) error {
		validators := deviceDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	domainMixin := schema.Domain{}.Mixin()
	domainMixinFields0 := domainMixin[0].Fields()
	_ = domainMixinFields0
	domainMixinFields1 := domainMixin[1].Fields()
	_ = domainMixinFields1
	domainFields := schema.Domain{}.Fields()
	_ = domainFields
	// domainDescCreatedAt is the schema descriptor for created_at field.
	domainDescCreatedAt := domainMixinFields1[0].Descriptor()
	// domain.DefaultCreatedAt holds the default value on creation for the created_at field.
	domain.DefaultCreatedAt = domainDescCreatedAt.Default.(func() time.Time)
	// domainDescUpdatedAt is the schema descriptor for updated_at field.
	domainDescUpdatedAt := domainMixinFields1[1].Descriptor()
	// domain.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	domain.DefaultUpdatedAt = domainDescUpdatedAt.Default.(func() time.Time)
	// domain.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	domain.UpdateDefaultUpdatedAt = domainDescUpdatedAt.UpdateDefault.(func() time.Time)
	// domainDescTenantID is the schema descriptor for tenant_id field.
	domainDescTenantID := domainFields[0].Descriptor()
	// domain.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	domain.TenantIDValidator = domainDescTenantID.Validators[0].(func(string) error)
	// domainDescName is the schema descriptor for name field.
	domainDescName := domainFields[1].Descriptor()
	// domain.NameValidator is a validator for the "name" field. It is called by the builders before save.
	domain.NameValidator = func() func(string) error {
		validators := domainDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// domainDescIsVerified is the schema descriptor for is_verified field.
	domainDescIsVerified := domainFields[2].Descriptor()
	// domain.DefaultIsVerified holds the default value on creation for the is_verified field.
	domain.DefaultIsVerified = domainDescIsVerified.Default.(bool)
	// domainDescID is the schema descriptor for id field.
	domainDescID := domainMixinFields0[0].Descriptor()
	// domain.DefaultID holds the default value on creation for the id field.
	domain.DefaultID = domainDescID.Default.(func() string)
	// domain.IDValidator is a validator for the "id" field. It is called by the builders before save.
	domain.IDValidator = func() func(string) error {
		validators := domainDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	driveMixin := schema.Drive{}.Mixin()
	driveMixinFields0 := driveMixin[0].Fields()
	_ = driveMixinFields0
	driveMixinFields1 := driveMixin[1].Fields()
	_ = driveMixinFields1
	driveFields := schema.Drive{}.Fields()
	_ = driveFields
	// driveDescCreatedAt is the schema descriptor for created_at field.
	driveDescCreatedAt := driveMixinFields1[0].Descriptor()
	// drive.DefaultCreatedAt holds the default value on creation for the created_at field.
	drive.DefaultCreatedAt = driveDescCreatedAt.Default.(func() time.Time)
	// driveDescUpdatedAt is the schema descriptor for updated_at field.
	driveDescUpdatedAt := driveMixinFields1[1].Descriptor()
	// drive.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	drive.DefaultUpdatedAt = driveDescUpdatedAt.Default.(func() time.Time)
	// drive.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	drive.UpdateDefaultUpdatedAt = driveDescUpdatedAt.UpdateDefault.(func() time.Time)
	// driveDescTenantID is the schema descriptor for tenant_id field.
	driveDescTenantID := driveFields[0].Descriptor()
	// drive.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	drive.TenantIDValidator = driveDescTenantID.Validators[0].(func(string) error)
	// driveDescOwnerID is the schema descriptor for owner_id field.
	driveDescOwnerID := driveFields[1].Descriptor()
	// drive.OwnerIDValidator is a validator for the "owner_id" field. It is called by the builders before save.
	drive.OwnerIDValidator = driveDescOwnerID.Validators[0].(func(string) error)
	// driveDescName is the schema descriptor for name field.
	driveDescName := driveFields[2].Descriptor()
	// drive.NameValidator is a validator for the "name" field. It is called by the builders before save.
	drive.NameValidator = func() func(string) error {
		validators := driveDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// driveDescStorageUsed is the schema descriptor for storage_used field.
	driveDescStorageUsed := driveFields[4].Descriptor()
	// drive.DefaultStorageUsed holds the default value on creation for the storage_used field.
	drive.DefaultStorageUsed = driveDescStorageUsed.Default.(int64)
	// driveDescID is the schema descriptor for id field.
	driveDescID := driveMixinFields0[0].Descriptor()
	// drive.DefaultID holds the default value on creation for the id field.
	drive.DefaultID = driveDescID.Default.(func() string)
	// drive.IDValidator is a validator for the "id" field. It is called by the builders before save.
	drive.IDValidator = func() func(string) error {
		validators := driveDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	driveitemMixin := schema.DriveItem{}.Mixin()
	driveitemMixinFields0 := driveitemMixin[0].Fields()
	_ = driveitemMixinFields0
	driveitemMixinFields1 := driveitemMixin[1].Fields()
	_ = driveitemMixinFields1
	driveitemFields := schema.DriveItem{}.Fields()
	_ = driveitemFields
	// driveitemDescCreatedAt is the schema descriptor for created_at field.
	driveitemDescCreatedAt := driveitemMixinFields1[0].Descriptor()
	// driveitem.DefaultCreatedAt holds the default value on creation for the created_at field.
	driveitem.DefaultCreatedAt = driveitemDescCreatedAt.Default.(func() time.Time)
	// driveitemDescUpdatedAt is the schema descriptor for updated_at field.
	driveitemDescUpdatedAt := driveitemMixinFields1[1].Descriptor()
	// driveitem.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	driveitem.DefaultUpdatedAt = driveitemDescUpdatedAt.Default.(func() time.Time)
	// driveitem.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	driveitem.UpdateDefaultUpdatedAt = driveitemDescUpdatedAt.UpdateDefault.(func() time.Time)
	// driveitemDescTenantID is the schema descriptor for tenant_id field.
	driveitemDescTenantID := driveitemFields[0].Descriptor()
	// driveitem.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	driveitem.TenantIDValidator = driveitemDescTenantID.Validators[0].(func(string) error)
	// driveitemDescDriveID is the schema descriptor for drive_id field.
	driveitemDescDriveID := driveitemFields[1].Descriptor()
	// driveitem.DriveIDValidator is a validator for the "drive_id" field. It is called by the builders before save.
	driveitem.DriveIDValidator = driveitemDescDriveID.Validators[0].(func(string) error)
	// driveitemDescParentID is the schema descriptor for parent_id field.
	driveitemDescParentID := driveitemFields[2].Descriptor()
	// driveitem.ParentIDValidator is a validator for the "parent_id" field. It is called by the builders before save.
	driveitem.ParentIDValidator = driveitemDescParentID.Validators[0].(func(string) error)
	// driveitemDescName is the schema descriptor for name field.
	driveitemDescName := driveitemFields[4].Descriptor()
	// driveitem.NameValidator is a validator for the "name" field. It is called by the builders before save.
	driveitem.NameValidator = func() func(string) error {
		validators := driveitemDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// driveitemDescMimeType is the schema descriptor for mime_type field.
	driveitemDescMimeType := driveitemFields[6].Descriptor()
	// driveitem.MimeTypeValidator is a validator for the "mime_type" field. It is called by the builders before save.
	driveitem.MimeTypeValidator = driveitemDescMimeType.Validators[0].(func(string) error)
	// driveitemDescID is the schema descriptor for id field.
	driveitemDescID := driveitemMixinFields0[0].Descriptor()
	// driveitem.DefaultID holds the default value on creation for the id field.
	driveitem.DefaultID = driveitemDescID.Default.(func() string)
	// driveitem.IDValidator is a validator for the "id" field. It is called by the builders before save.
	driveitem.IDValidator = func() func(string) error {
		validators := driveitemDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	groupMixin := schema.Group{}.Mixin()
	groupMixinFields0 := groupMixin[0].Fields()
	_ = groupMixinFields0
	groupMixinFields1 := groupMixin[1].Fields()
	_ = groupMixinFields1
	groupFields := schema.Group{}.Fields()
	_ = groupFields
	// groupDescCreatedAt is the schema descriptor for created_at field.
	groupDescCreatedAt := groupMixinFields1[0].Descriptor()
	// group.DefaultCreatedAt holds the default value on creation for the created_at field.
	group.DefaultCreatedAt = groupDescCreatedAt.Default.(func() time.Time)
	// groupDescUpdatedAt is the schema descriptor for updated_at field.
	groupDescUpdatedAt := groupMixinFields1[1].Descriptor()
	// group.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	group.DefaultUpdatedAt = groupDescUpdatedAt.Default.(func() time.Time)
	// group.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	group.UpdateDefaultUpdatedAt = groupDescUpdatedAt.UpdateDefault.(func() time.Time)
	// groupDescTenantID is the schema descriptor for tenant_id field.
	groupDescTenantID := groupFields[0].Descriptor()
	// group.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	group.TenantIDValidator = groupDescTenantID.Validators[0].(func(string) error)
	// groupDescIdpID is the schema descriptor for idp_id field.
	groupDescIdpID := groupFields[1].Descriptor()
	// group.IdpIDValidator is a validator for the "idp_id" field. It is called by the builders before save.
	group.IdpIDValidator = groupDescIdpID.Validators[0].(func(string) error)
	// groupDescExternalID is the schema descriptor for external_id field.
	groupDescExternalID := groupFields[2].Descriptor()
	// group.ExternalIDValidator is a validator for the "external_id" field. It is called by the builders before save.
	group.ExternalIDValidator = func() func(string) error {
		validators := groupDescExternalID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(external_id string) error {
			for _, fn := range fns {
				if err := fn(external_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// groupDescName is the schema descriptor for name field.
	groupDescName := groupFields[3].Descriptor()
	// group.NameValidator is a validator for the "name" field. It is called by the builders before save.
	group.NameValidator = func() func(string) error {
		validators := groupDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// groupDescID is the schema descriptor for id field.
	groupDescID := groupMixinFields0[0].Descriptor()
	// group.DefaultID holds the default value on creation for the id field.
	group.DefaultID = groupDescID.Default.(func() string)
	// group.IDValidator is a validator for the "id" field. It is called by the builders before save.
	group.IDValidator = func() func(string) error {
		validators := groupDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	idpproviderMixin := schema.IdpProvider{}.Mixin()
	idpproviderMixinFields0 := idpproviderMixin[0].Fields()
	_ = idpproviderMixinFields0
	idpproviderMixinFields1 := idpproviderMixin[1].Fields()
	_ = idpproviderMixinFields1
	idpproviderFields := schema.IdpProvider{}.Fields()
	_ = idpproviderFields
	// idpproviderDescCreatedAt is the schema descriptor for created_at field.
	idpproviderDescCreatedAt := idpproviderMixinFields1[0].Descriptor()
	// idpprovider.DefaultCreatedAt holds the default value on creation for the created_at field.
	idpprovider.DefaultCreatedAt = idpproviderDescCreatedAt.Default.(func() time.Time)
	// idpproviderDescUpdatedAt is the schema descriptor for updated_at field.
	idpproviderDescUpdatedAt := idpproviderMixinFields1[1].Descriptor()
	// idpprovider.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	idpprovider.DefaultUpdatedAt = idpproviderDescUpdatedAt.Default.(func() time.Time)
	// idpprovider.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	idpprovider.UpdateDefaultUpdatedAt = idpproviderDescUpdatedAt.UpdateDefault.(func() time.Time)
	// idpproviderDescTenantID is the schema descriptor for tenant_id field.
	idpproviderDescTenantID := idpproviderFields[0].Descriptor()
	// idpprovider.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	idpprovider.TenantIDValidator = idpproviderDescTenantID.Validators[0].(func(string) error)
	// idpproviderDescName is the schema descriptor for name field.
	idpproviderDescName := idpproviderFields[2].Descriptor()
	// idpprovider.NameValidator is a validator for the "name" field. It is called by the builders before save.
	idpprovider.NameValidator = func() func(string) error {
		validators := idpproviderDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// idpproviderDescProtoConfig is the schema descriptor for proto_config field.
	idpproviderDescProtoConfig := idpproviderFields[3].Descriptor()
	// idpprovider.DefaultProtoConfig holds the default value on creation for the proto_config field.
	idpprovider.DefaultProtoConfig = idpproviderDescProtoConfig.Default.(string)
	// idpproviderDescID is the schema descriptor for id field.
	idpproviderDescID := idpproviderMixinFields0[0].Descriptor()
	// idpprovider.DefaultID holds the default value on creation for the id field.
	idpprovider.DefaultID = idpproviderDescID.Default.(func() string)
	// idpprovider.IDValidator is a validator for the "id" field. It is called by the builders before save.
	idpprovider.IDValidator = func() func(string) error {
		validators := idpproviderDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	tenantMixin := schema.Tenant{}.Mixin()
	tenantMixinFields0 := tenantMixin[0].Fields()
	_ = tenantMixinFields0
	tenantMixinFields1 := tenantMixin[1].Fields()
	_ = tenantMixinFields1
	tenantFields := schema.Tenant{}.Fields()
	_ = tenantFields
	// tenantDescCreatedAt is the schema descriptor for created_at field.
	tenantDescCreatedAt := tenantMixinFields1[0].Descriptor()
	// tenant.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenant.DefaultCreatedAt = tenantDescCreatedAt.Default.(func() time.Time)
	// tenantDescUpdatedAt is the schema descriptor for updated_at field.
	tenantDescUpdatedAt := tenantMixinFields1[1].Descriptor()
	// tenant.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tenant.DefaultUpdatedAt = tenantDescUpdatedAt.Default.(func() time.Time)
	// tenant.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tenant.UpdateDefaultUpdatedAt = tenantDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tenantDescAlias is the schema descriptor for alias field.
	tenantDescAlias := tenantFields[0].Descriptor()
	// tenant.AliasValidator is a validator for the "alias" field. It is called by the builders before save.
	tenant.AliasValidator = func() func(string) error {
		validators := tenantDescAlias.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(alias string) error {
			for _, fn := range fns {
				if err := fn(alias); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// tenantDescName is the schema descriptor for name field.
	tenantDescName := tenantFields[1].Descriptor()
	// tenant.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tenant.NameValidator = func() func(string) error {
		validators := tenantDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// tenantDescID is the schema descriptor for id field.
	tenantDescID := tenantMixinFields0[0].Descriptor()
	// tenant.DefaultID holds the default value on creation for the id field.
	tenant.DefaultID = tenantDescID.Default.(func() string)
	// tenant.IDValidator is a validator for the "id" field. It is called by the builders before save.
	tenant.IDValidator = func() func(string) error {
		validators := tenantDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userMixinFields1 := userMixin[1].Fields()
	_ = userMixinFields1
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields1[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields1[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescTenantID is the schema descriptor for tenant_id field.
	userDescTenantID := userFields[0].Descriptor()
	// user.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	user.TenantIDValidator = userDescTenantID.Validators[0].(func(string) error)
	// userDescIdpID is the schema descriptor for idp_id field.
	userDescIdpID := userFields[1].Descriptor()
	// user.IdpIDValidator is a validator for the "idp_id" field. It is called by the builders before save.
	user.IdpIDValidator = userDescIdpID.Validators[0].(func(string) error)
	// userDescExternalID is the schema descriptor for external_id field.
	userDescExternalID := userFields[2].Descriptor()
	// user.ExternalIDValidator is a validator for the "external_id" field. It is called by the builders before save.
	user.ExternalIDValidator = func() func(string) error {
		validators := userDescExternalID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(external_id string) error {
			for _, fn := range fns {
				if err := fn(external_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[3].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescDisplayName is the schema descriptor for display_name field.
	userDescDisplayName := userFields[4].Descriptor()
	// user.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	user.DisplayNameValidator = userDescDisplayName.Validators[0].(func(string) error)
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[5].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	// user.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	user.RoleValidator = userDescRole.Validators[0].(func(string) error)
	// userDescID is the schema descriptor for id field.
	userDescID := userMixinFields0[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() string)
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = func() func(string) error {
		validators := userDescID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(id string) error {
			for _, fn := range fns {
				if err := fn(id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
}
